<p>
    I understand that by submitting this application I am accepting the undertakings below; that they will be recorded
    on the licence; that failure to comply with the conditions or undertakings recorded on the licence may result in the
    licence being revoked, suspended or curtailed; and that failure to comply with these conditions is also a criminal
    offence.
</p>
<ul class="list--bullet">
    <li>The laws relating to the driving and operation of vehicles used under this licence are observed;</li>
    <li>
        The rules on drivers’ hours and tachographs are observed and proper records are kept, and that these are made
        available on request;
    </li>
    <li>Vehicles do not carry more than the permitted number of passengers;</li>
    <li>Vehicles operate within speed limits;</li>
    <li>Vehicles, including hired vehicles and, are kept in a fit and serviceable condition;</li>
    <li>
        Drivers report promptly any defects or symptoms of defects that could prevent the safe operation of vehicles,
        and that any defects are recorded in writing;
    </li>
    <li>
        Records are kept (for at least 15 months) of all driver reports that record defects, and all safety inspection,
        routine maintenance and vehicle repair reports, and that these are made available on request;
    </li>
    <li>
        Furthermore, I will notify the Traffic Commissioner of any convictions against myself, or the company, business
        partner(s), the company director(s) or nominated Transport Manager(s) named in this application, or employees or
        agents of the applicant for this licence and, if the licence is issued, convictions against the licence holder
        or employees or agents of the licence holder;
    </li>
    <li>
        I will ensure that the Traffic Commissioner is notified within 28 days of any other changes, for example a
        change to the proposed maintenance arrangements; a change in the financial status of the licence holder (e.g. if
        placed in liquidation or receivership); or a change to Limited Company status or partnership, that might affect
        the licence, if issued.
    </li>
    %s
</ul>
%s