<ul class="bullet">
    <li>you have read the <a href="https://www.gov.uk/guidance/international-road-haulage-removal-permits" target="_blank">guidance notes</a> on how to use ECMT international removal permits.</li>
    <li>you will comply fully with the conditions of use under which the permits may be used.</li>
    <li>you understand you must obtain a Certificate of Compliance and a Certificate of Roadworthiness for each vehicle and trailer you intend to use.</li>
    <li>your driver will carry the permit and the certificates for the entire outbound and return journey and present it to any competent authority or inspectors.</li>
    <li>your company uses specialised equipment and staff to undertake removal operations.</li>
    <li>you understand that this permit can only be used for international removals between ECMT member countries.</li>
    <li>you understand that, when transiting, you can only use it to deliver removal goods and business possessions to other ECMT countries.</li>
</ul>
