<ul class="govuk-list govuk-list--bullet">
    <li>have read and agree to follow <a href="https://www.gov.uk/guidance/ecmt-international-road-haulage-permits" target="_blank">the rules on how to use Short-term ECMT permits<span class="govuk-visually-hidden">(link opens in a new window)</span></a></li>
    <li>understand that this permit is for transiting through EU member states to non-EU countries who are ECMT members, including Switzerland</li>
    <li>understand that this permit is for a third cross-trade trip within 7 days</li>
    <li>understand that Short-term permits are not valid for Austria</li>
    <li>will only use vehicles that comply with the Euro emissions standard for each permit</li>
    <li>understand that a Certificate of Compliance and a Certificate of Roadworthiness is required for each vehicle and trailer you intend to use</li>
    <li>understand that Short-term ECMT permits can only be used for 30 consecutive days during the calendar year they have been issued</li>
    <li>will complete the permit start and end dates before starting your journey</li>
    <li>must complete the corresponding logbook with full journey details before the start of a journey</li>
    <li>understand the logbook must be returned to DVSA within 2 weeks after returning to the UK</li>
</ul>
<p class="govuk-body">Your driver must also carry the permit and corresponding logbook, and the certificates for the entire outbound and return journey and present it to any competent authority or inspectors.</p>
