<ul class="bullet">
    <li>your vehicle must carry a warning triangle when travelling in Europe.</li>
    <li>your driver must carry the Certificate of Roadworthiness and the Certificate of Compliance for the entire outbound and return journey and present it to any competent authority or inspectors.</li>
    <li>you understand the Certificate of Roadworthiness will expire on the same day as the MOT certificate.</li>
</ul>
