<ul class="bullet">
    <li>you have read the <a href="https://www.gov.uk/guidance/international-authorisations-and-permits-for-road-haulage" target="_blank">guidance notes</a> on how to use Short-term ECMT permits.</li>
    <li>you will comply fully with the conditions of use under which the permits may be used.</li>
    <li>you understand that this permit is for transiting through EU member states to non-EU countries, including Switzerland.</li>
    <li>you understand that this permit is for cross-trade for the haulage of goods for hire or reward between two EU countries by a vehicle registered in a different EU country.</li>
    <li>you will only use the appropriate Euro emission standard vehicle that the permit allows.</li>
    <li>you understand you must obtain a Certificate of Compliance and a Certificate of Roadworthiness for each vehicle and trailer you intend to use.</li>
    <li>your driver must carry the permit and corresponding logbook, and the certificates for the entire outbound and return journey and present it to any competent authority or inspectors.</li>
    <li>you understand that Short-term ECMT permits can only be used for 30 consecutive days during the calendar year they have been issued.</li>
    <li>you will fill the paper permit with the start and end date before starting your journey.</li>
</ul>
