<li>
    The operator shall, during the life of the restricted licence, keep separate records of all time spent and the gross
    and net income earned monthly by them from all occupations ( with supporting detailed records from which these sums
    are derived) to enable the main occupation to be determined by the Traffic Commissioner at any time. Records shall
    be supported by primary evidence such as payslips, P60 documents, booking diaries, invoices and tachograph records.
    Copies of the records shall be made available to the DVSA or OTC officers on request.
</li>
<li>
    Should the operator no longer meet the requirements to hold a restricted licence then they will either surrender it
    or apply for standard licence.
</li>
