<p>
    <strong>
        I understand that by submitting this application I am accepting the additional undertakings below; that they will be
        recorded on the licence; that failure to comply with the conditions or undertakings recorded on the licence may
        result in the licence being revoked, suspended or curtailed; and that failure to comply with these conditions is
        a criminal offence.
    </strong>
</p>
<ul class="list--bullet">
    <li>
        I must be able to prove that I have a formal arrangement for access at all times to at least one vehicle
        registered or in circulation in the UK. This could be by specifying a vehicle for use under an operator’s licence or
        by demonstrating on request that I (the licence holder) have a vehicle available, so that vehicles may be either
        wholly owned or held under a hire-purchase, hire / leasing or other type of formal arrangement;
    </li>
    <li>
        I have an establishment in Northern Ireland with premises in which I keep core business documents. These include
        (as a minimum) accounting and personnel management documents and data on driving time and rest. I understand
        that the use of a PO Box or third party address is not permitted.
    </li>
</ul>
%s
%s
<strong>
    Please see the licence undertakings below as a reminder of your existing obligations.
</strong>
<ul class="list--bullet">
    <li>The laws relating to the driving and operation of vehicles used under this licence are observed;</li>
    <li>
        The rules on drivers’ hours and tachographs are observed and proper records are kept, and that these are made
        available on request;
    </li>
    <li>Vehicles and trailers are not overloaded;</li>
    <li>Vehicles operate within speed limits;</li>
    <li>Vehicles and trailers, including hired vehicles and trailers, are kept in a fit and serviceable condition;</li>
    <li>
        Drivers report promptly any defects or symptoms of defects that could prevent the safe operation of vehicles
        and/or trailers, and that any defects are recorded in writing;
    </li>
    <li>
        Records are kept (for at least 15 months) of all driver reports that record defects, and all safety inspection,
        routine maintenance and vehicle repair reports, and that these are made available on request;
    </li>
    <li>
        In respect of each operating centre specified, that the number of vehicles and the number of trailers kept there
        will not exceed the maximum numbers authorised at each operating centre (which will be noted on the licence);
    </li>
    <li>An unauthorised operating centre is not used;</li>
    <li>
        Furthermore, I will notify the DfI of any penalties and unspent convictions against myself, or the company,
        business partner(s), the company directors, nominated transport manager(s) named in this application, or
        employees or agents of the applicant for this licence and, if the licence is issued, convictions against the
        licence holder or employees or agents of the licence holder;
    </li>
    <li>
        I will ensure that the DfI is notified within 28 days of any other changes, for example a change to the proposed
        maintenance arrangements; a change in the financial status of the licence holder (eg if placed in liquidation
        or receivership); or a change to Limited Company status or partnership, that might affect the licence, if
        issued.
    </li>
</ul>