<p>
    (a) The operator will advise the traffic commissioner of the make, model and registration number of vehicles used
    under that licence, and will advise of any changes.
</p>
<p>
    (b) In respect of any vehicle with eight or less passengers seats used under the licence, the operator will provide
    an audit trail to the traffic commissioner or any enforcement body on request, that demonstrates compliance with PSV
    requirements. This includes paperwork as to how in respect of any service separate fares were paid and one of the
    two conditions set out in Question 1 were met. Note this undertaking does not apply when the vehicle is being used
    under the provisions of Section 79A.
</p>
<p>
    (c) Each small vehicle to be used under the licence will have a V5C registration certificate, and the operator must
    possess and produce, when asked to do so, a document confirming this.
</p>
<p>
    (d) Each small vehicle will receive a full safety inspection (maximum every 10 weeks) in premises suitable for the
    vehicle to ensure that its roadworthiness is maintained. Records of all inspections must be kept in accordance with
    the Guide to Maintaining Roadworthiness.
</p>
<p>(e) At no time will the small vehicle carry more than eight passengers.</p>
<p>
    (f) The operator will at all times comply with the legislation in respect of the charging of separate fares and
    retain 12 months’ evidence of this compliance for each journey.
</p>
<p>
    (g) Drivers of small vehicles will carry with them documentary evidence that separate fares have been charged for
    the current journey.
</p>
<p>
    (h) The operator will not use a vehicle that does not meet the ECWVTA standards, British construction and use
    requirements or the Road Vehicles Approval Regulations 2009 (as amended).
</p>
<p>(i) The operator or driver will not break the alcohol laws.</p>