<ul class="bullet">
    <li>You have read the <a href="https://www.gov.uk/guidance/international-road-haulage-removal-permits" target="_blank">guidance notes</a> on how to use ECMT international removal permits.</li>
    <li>You will comply fully with the conditions of use under which the permits may be used.</li>
    <li>Your driver will carry the permit for the entire outbound and return journey and present it to any competent authority or inspectors.</li>
    <li>Your company uses specialised equipment and staff to undertake removal operations.</li>
    <li>You understand that this permit can only be used for international removals between ECMT member countries.</li>
    <li>You understand that, when transiting, you can only use it to deliver removal goods and business possessions to other ECMT countries.</li>
</ul>
