<div class="signature-box">

    <div class="govuk-inset-text">
        The licence holder is also the Transport Manager.
    </div>

    <hr />
    <div class="signature-box__digital-signature">
        <form>
            <div>
                <label class="signature-box__label">Licence holder and Transport Manager's signature</label>
                <span class="signature-box__value">Signed by using GOV.UK Verify</span>
            </div>

            <div>
                <label class="signature-box__label">Signed by</label>
                <span class="signature-box__value">%s</span>
            </div>

            <div>
                <label class="signature-box__label">Date of Birth</label>
                <span class="signature-box__value">%s</span>
            </div>
            <div>
                <label class="signature-box__label">Signature date</label>
                <span class="signature-box__value">%s</span>
            </div>
        </form>
    </div>
</div>