<p>
    <b>By submitting this form you are confirming your status as an internal transport manager, an external transport manager or both.</b>
</p>
<p>I confirm that:</p>
<ul class="list--bullet">
    <li>%s;</li>
</ul>
<?php
echo $this->HtmlPurifier($this->translate('tma-tm-declaration-drivers-administration'));
echo $this->HtmlPurifier($this->translate('tma-tm-declaration-drivers-management'));
echo $this->HtmlPurifier($this->translate('tma-tm-declaration-drivers-operations'));
echo $this->HtmlPurifier($this->translate('tma-tm-declaration-vehicle-administration'));
echo $this->HtmlPurifier($this->translate('tma-tm-declaration-vehicle-management'));
echo $this->HtmlPurifier($this->translate('tma-tm-declaration-licence-administration'));
echo $this->HtmlPurifier($this->translate('tma-tm-declaration-internal'));
echo $this->HtmlPurifier($this->translate('tma-tm-declaration-external'));
echo $this->HtmlPurifier($this->translate('tma-tm-declaration-warning'));
?>
