<h4>Condition 1</h4>
<p>The passengers
    must have been brought together for the purposes of making the journey by the driver or owner of the vehicle or
    by some other intermediary who is paid for. In addition each journey must have been advertised to the public, so
    as to create a genuine opportunity for members of the public to be carried on the particular journey in
    question, i.e. the journey is not an exclusive hiring for an individual or group, notwithstanding that separate
    fares are paid. Advertisement at a place of worship, a place of work, a club or other voluntary association for
    the information of people present at those places, or in periodicals circulated wholly or mainly among such
    persons, does not count as advertisement to the general public. Finally, in the event that there are multiple
    destinations, there should be differentiation of fares for the journey based on distance or time.
</p>
<h4>Condition 2</h4>
<p>
    The making of the agreement for the payment of separate fares must have been initiated by the driver or owner of
    the vehicle, or by some other intermediary who is paid for doing so – not by the passengers themselves, or any
    other party. In addition, as in condition 1, each journey must be advertised to the public beforehand as being
    open to passengers to be carried at separate fares.
</p>