<li>
    I undertake to have a formal arrangement in place for access at all times to at least one public service vehicle
    registered or in circulation in Great Britain. I will either provide details of a vehicle wholly owned by me and
    to be used under the licence or by demonstrating on request that I have access to a vehicle under a
    hire-purchase, hire/leasing agreement or other type of formal arrangement.
</li>