<ul class="bullet">
    <li>I have read the <a href="https://www.gov.uk/guidance/international-authorisations-and-permits-for-road-haulage" target="_blank">Guidance Notes</a> on how to use ECMT permits.</li>
    <li>I understand if a permit is issued it may exclude travel to Austria, Greece, Hungary, Italy and Russia.</li>
    <li>I understand that if a permit is issued I will be issued with a corresponding logbook which I must complete with full journey details before the start of a journey.</li>
    <li>I understand that I must carry a permit and corresponding logbook for the entire outbound and return journey.</li>
</ul>