<p>
    <b>By submitting this form you are confirming your status as an internal transport manager, an external transport manager or both.</b>
</p>
<?php
echo $this->htmlPurifier($this->translate('tma-tm-declaration-drivers-administration'));
echo $this->htmlPurifier($this->translate('tma-tm-declaration-drivers-management'));
echo $this->htmlPurifier($this->translate('tma-tm-declaration-drivers-operations'));
echo $this->htmlPurifier($this->translate('tma-tm-declaration-vehicle-administration'));
echo $this->htmlPurifier($this->translate('tma-tm-declaration-vehicle-management'));
echo $this->htmlPurifier($this->translate('tma-tm-declaration-licence-administration'));
echo $this->htmlPurifier($this->translate('tma-tm-declaration-internal'));
echo $this->htmlPurifier($this->translate('tma-tm-declaration-external'));
echo $this->htmlPurifier($this->translate('tma-tm-declaration-warning'));
?>
