<p>Dear operator,</p>

<p>Important documentation relating to your Operator&rsquo;s Licence continuation for <?php echo $this->licNo; ?>
has been placed in your Self Service correspondence inbox.</p>

<p>This is the English version of the document and we will arrange for a Welsh version of it to be sent to you as soon as possible.</p>

<p>Please note that you must sign it and return it to the office as soon as possible, highlighting changes to any of the details.</p>

<p>
    <a href="<?php echo $this->url; ?>">Sign in to your account</a>
</p>
