<h2>WELSH</h2>

<p>Hi <?php echo $this->name ?>,</p>

<p>
    <strong><?php echo $this->organisation ?></strong> have named you as a Transport Manager on the Vehicle Operator Licence
    <strong><?php echo $this->reference ?></strong>.
</p>

<p>
    <a href="<?php echo $this->signInLink?>">Sign in to my account</a>
</p>

<p>
    Experiencing problems?<br>
    If you are unable to access the form online using the link above, this help guide provides answers to
    frequently asked questions. You can also contact us at <a href="mailto:assisted.digital@otc.gsi.gov.uk">assisted.digital@otc.gsi.gov.uk</a>
    If for whatever reason you are unable to complete the Transport Manager form online, you can download a
    paper copy of the <a href="https://www.gov.uk/government/publications/application-to-add-a-transport-manager-to-a-licence-tm1">TM1 form here</a>. You will need to complete the TM1 form and mail it to us.
</p>