<strong><?php

if ($periodNameKey) {
    echo($this->escapeHtml($this->translate($periodNameKey, 'snapshot')));
} else {
    $translated = sprintf(
        $this->translate('permits.check-your-answers.no-of-permits.year', 'snapshot'),
        $validityYear
    );

    echo($this->escapeHtml($translated));
}

?></strong><?php

foreach ($emissionsCategories as $emissionsCategory) {

    if ($emissionsCategory['count'] > 0) {
        $translatedKey = $this->translate($emissionsCategory['key'], 'snapshot');

        $line = sprintf(
            $this->translate('qanda.common.no-of-permits.emissions-category.line', 'snapshot'),
            $emissionsCategory['count'],
            $translatedKey
        );

        echo('<br>' . $this->escapeHtml($line));
    }
}
