
    /**
     * Set the <?php echo strtolower($this->getReadableStringFromName((isset($item['property']) ? $item['property'] : $field['@attributes'][$item['ref']]))); ?>

     *
<?php if (in_array($item['type'], array('oneToMany', 'manyToMany'))): ?>
     * @param \Doctrine\Common\Collections\ArrayCollection $<?php echo $this->formatParamName($item); ?> collection being set as the value
<?php elseif (in_array($item['type'], array('oneToOne', 'manyToOne'))): ?>
     * @param \<?php echo $field['@attributes']['target-entity']; ?> $<?php echo $this->formatParamName($item); ?> entity being set as the value
<?php else: ?>
     * @param <?php echo $this->getPhpTypeFromType($field['@attributes']['type']); ?> $<?php echo $this->formatParamName($item); ?> new value being set
<?php endif; ?>
     *
     * @return <?php echo $fluidReturn; ?>

     */
    public function set<?php echo ucfirst($this->formatPropertyName($item)); ?>($<?php echo $this->formatParamName($item); ?>)
    {
        $this-><?php echo $this->formatPropertyName($item); ?> = $<?php echo $this->formatParamName($item); ?>;

        return $this;
    }

    /**
     * Get the <?php echo strtolower($this->getReadableStringFromName($this->formatPropertyName($item))); ?>

     *
<?php if (in_array($item['type'], array('oneToMany', 'manyToMany'))): ?>
     * @return \Doctrine\Common\Collections\ArrayCollection<?php elseif (in_array($item['type'], array('oneToOne', 'manyToOne'))): ?>
     * @return \<?php echo $field['@attributes']['target-entity']; ?>
<?php elseif ($this->getPhpTypeFromType($field['@attributes']['type']) === '\DateTime'): ?>
     * @param bool $asDateTime If true will always return a \DateTime (or null) never a string datetime
     *
     * @return <?php echo $this->getPhpTypeFromType($field['@attributes']['type']); ?>
<?php else: ?>
     * @return <?php echo $this->getPhpTypeFromType($field['@attributes']['type']); ?>
<?php endif; ?>
<?php if ($item['type'] === 'field' && $this->getPhpTypeFromType($field['@attributes']['type']) === '\DateTime'): ?>

     */
    public function get<?php echo ucfirst($this->formatPropertyName($item)); ?>($asDateTime = false)
    {
        if ($asDateTime === true) {
            return $this->asDateTime($this-><?php echo $this->formatPropertyName($item); ?>);
        }

        return $this-><?php echo $this->formatPropertyName($item); ?>;
    }
<?php else: ?>

     */
    public function get<?php echo ucfirst($this->formatPropertyName($item)); ?>()
    {
        return $this-><?php echo $this->formatPropertyName($item); ?>;
    }
<?php endif; ?>
<?php if (in_array($item['type'], array('oneToMany', 'manyToMany'))): ?>

    /**
     * Add a <?php echo strtolower($this->getReadableStringFromName($this->formatPropertyName($item))); ?>

     *
<?php if (in_array($item['type'], array('oneToMany', 'manyToMany'))): ?>
     * @param \Doctrine\Common\Collections\ArrayCollection $<?php echo $this->formatPropertyName($item); ?> collection being added
<?php elseif (in_array($item['type'], array('oneToOne', 'manyToOne'))): ?>
     * @param \<?php echo $field['@attributes']['target-entity']; ?> $<?php echo $this->formatPropertyName($item); ?> entity being added
<?php else: ?>
     * @param <?php echo $this->getPhpTypeFromType($field['@attributes']['type']); ?> $<?php echo $this->formatPropertyName($item); ?> value being added
<?php endif; ?>
     *
     * @return <?php echo $fluidReturn; ?>

     */
    public function add<?php echo ucfirst($this->formatPropertyName($item)); ?>($<?php echo $this->formatPropertyName($item); ?>)
    {
        if ($<?php echo $this->formatPropertyName($item); ?> instanceof ArrayCollection) {
            $this-><?php echo $this->formatPropertyName($item); ?> = new ArrayCollection(
                array_merge(
                    $this-><?php echo $this->formatPropertyName($item); ?>->toArray(),
                    $<?php echo $this->formatPropertyName($item); ?>->toArray()
                )
            );
        } elseif (!$this-><?php echo $this->formatPropertyName($item); ?>->contains($<?php echo $this->formatPropertyName($item); ?>)) {
            $this-><?php echo $this->formatPropertyName($item); ?>->add($<?php echo $this->formatPropertyName($item); ?>);
        }

        return $this;
    }

    /**
     * Remove a <?php echo strtolower($this->getReadableStringFromName($this->formatPropertyName($item))); ?>

     *
<?php if (in_array($item['type'], array('oneToMany', 'manyToMany'))): ?>
     * @param \Doctrine\Common\Collections\ArrayCollection $<?php echo $this->formatPropertyName($item); ?> collection being removed
<?php elseif (in_array($item['type'], array('oneToOne', 'manyToOne'))): ?>
     * @param \<?php echo $field['@attributes']['target-entity']; ?> $<?php echo $this->formatPropertyName($item); ?> entity being removed
<?php else: ?>
     * @param <?php echo $this->getPhpTypeFromType($field['@attributes']['type']); ?> $<?php echo $this->formatPropertyName($item); ?> value being removed
<?php endif; ?>
     *
     * @return <?php echo $fluidReturn; ?>

     */
    public function remove<?php echo ucfirst($this->formatPropertyName($item)); ?>($<?php echo $this->formatPropertyName($item); ?>)
    {
        if ($this-><?php echo $this->formatPropertyName($item); ?>->contains($<?php echo $this->formatPropertyName($item); ?>)) {
            $this-><?php echo $this->formatPropertyName($item); ?>->removeElement($<?php echo $this->formatPropertyName($item); ?>);
        }

        return $this;
    }
<?php endif; ?>