<?php

return array(
    // Mapping configs allow us to override the name of an association mapping generated by doctrine
    'mappingConfig' => array(
        // Entity namespace
        'Dvsa\Olcs\Api\Entity\RefData' => [
            'metadata' => [
                'skipManyToMany' => true
            ]
        ],
        /*'Dvsa\Olcs\Api\Entity\Country' => [
            'metadata' => [
                'skipManyToMany' => true
            ]
        ],*/
        'classNameForTable' => [
           'txn' => 'Transaction',
           'fee_txn' => 'FeeTransaction'
        ],
        'fieldNameForColumn' => [
           'fee_txn' => [
               'txn_id' => 'transaction',
               'reversed_fee_txn_id' => 'reversedFeeTransaction'
           ]
        ]
    ),
    'namespaces' => include(__DIR__ . '/../../module/Api/config/namespace.config.php'),
    'organisation' => array(
        'company_cert_seen' => array(
            'type' => 'yesno'
        ),
        'confirm_share_vehicle_info' => array(
            'type' => 'yesno'
        ),
        'confirm_share_trailer_info' => array(
            'type' => 'yesno'
        ),
        'is_irfo' => array(
            'type' => 'yesno'
        ),
        'allow_email' => array(
            'type' => 'yesno'
        ),
        'irfo_contact_details_id' => array(
            'cascade' => array(
                'persist'
            )
        ),
    ),
    'country' => array(
        'is_member_state' => array(
            'type' => 'yesno'
        )
    ),
    'address' => array(
        'paon_desc' => array(
            'property' => 'addressLine2'
        ),
        'saon_desc' => array(
            'property' => 'addressLine1'
        ),
        'street' => array(
            'property' => 'addressLine3'
        ),
        'locality' => array(
            'property' => 'addressLine4'
        )
    ),
    'contact_details' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'contactDetail'
            )
        ),
        'organisation_id' => array(
            'inversedBy' => array(
                'entity' => 'Organisation',
                'property' => 'contactDetail'
            )
        ),
        'address_id' => array(
            'inversedBy' => array(
                'entity' => 'Address',
                'property' => 'contactDetail'
            ),
            'cascade' => array(
                'persist'
            )
        ),
        'person_id' => array(
            'cascade' => array(
                'persist'
            ),
            'inversedBy' => array(
                'entity' => 'Person',
                'property' => 'contactDetail'
            )
        ),
        'written_permission_to_engage' => array(
            'type' => 'yesno'
        )
    ),
    'user' => array(
        'account_disabled' => array(
            'type' => 'yesno'
        ),
        'must_reset_password' => array(
            'type' => 'yesno'
        ),
        'contact_details_id' => array(
            'cascade' => array(
                'persist'
            )
        ),
        'partner_contact_details_id' => array(
            'cascade' => array(
                'persist'
            )
        ),
        'transport_manager_id' => array(
            'inversedBy' => array(
                'entity' => 'TransportManager',
                'property' => 'user'
            ),
        ),
        'translate_to_welsh' => array(
            'type' => 'yesno'
        ),
        'local_authority_id' => array(
            'inversedBy' => array(
                'entity' => 'LocalAuthority',
                'property' => 'user'
            ),
        ),
    ),
    'licence' => array(
        'organisation_id' => array(
            'inversedBy' => array(
                'entity' => 'Organisation',
                'property' => 'licence',
            ),
            'cascade' => array(
                'persist',
            ),
        ),
        'correspondence_cd_id' => array(
            'cascade' => array(
                'persist',
            ),
        ),
        'safety_ins' => array(
            'type' => 'yesno'
        ),
        'safety_ins_varies' => array(
            'type' => 'yesnonull'
        ),
        'ni_flag' => array(
            'type' => 'yesnonull'
        ),
        'translate_to_welsh' => array(
            'type' => 'yesno'
        ),
        'is_maintenance_suitable' => array(
            'type' => 'yesnonull'
        )
    ),
    'application' => array(
        'ni_flag' => array(
            'type' => 'yesnonull'
        ),
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'application'
            ),
            'cascade' => array(
                'persist'
            )
        ),
        'has_entered_reg' => array(
            'type' => 'yesnonull'
        ),
        'bankrupt' => array(
            'type' => 'yesnonull'
        ),
        'administration' => array(
            'type' => 'yesnonull'
        ),
        'disqualified' => array(
            'type' => 'yesnonull'
        ),
        'liquidation' => array(
            'type' => 'yesnonull'
        ),
        'receivership' => array(
            'type' => 'yesnonull'
        ),
        'insolvency_confirmation' => array(
            'type' => 'yesno'
        ),
        'safety_confirmation' => array(
            'type' => 'yesno'
        ),
        'declaration_confirmation' => array(
            'type' => 'yesno'
        ),
        'financial_evidence_uploaded' => array(
            'type' => 'smallint'
        ),
        'prev_has_licence' => array(
            'type' => 'yesnonull'
        ),
        'prev_had_licence' => array(
            'type' => 'yesnonull'
        ),
        'prev_been_refused' => array(
            'type' => 'yesnonull'
        ),
        'prev_been_revoked' => array(
            'type' => 'yesnonull'
        ),
        'prev_been_at_pi' => array(
            'type' => 'yesnonull'
        ),
        'prev_been_disqualified_tc' => array(
            'type' => 'yesnonull'
        ),
        'prev_purchased_assets' => array(
            'type' => 'yesnonull'
        ),
        'override_ooo' => array(
            'type' => 'yesno'
        ),
        'prev_conviction' => array(
            'type' => 'yesnonull'
        ),
        'convictions_confirmation' => array(
            'type' => 'yesno'
        ),
        'psv_operate_small_vhl' => array(
            'type' => 'yesnonull'
        ),
        'psv_small_vhl_confirmation' => array(
            'type' => 'yesnonull'
        ),
        'psv_no_small_vhl_confirmation' => array(
            'type' => 'yesnonull'
        ),
        'psv_limousines' => array(
            'type' => 'yesnonull'
        ),
        'psv_no_limousine_confirmation' => array(
            'type' => 'yesnonull'
        ),
        'psv_only_limousines_confirmation' => array(
            'type' => 'yesnonull'
        ),
        'is_maintenance_suitable' => array(
            'type' => 'yesnonull'
        ),
        'psv_medium_vhl_confirmation' => array(
            'type' => 'yesnonull'
        ),
    ),
    's4' => array(
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 's4'
            ),
        ),
        'surrender_licence' => array(
            'type' => 'yesno'
        ),
        'is_true_s4' => array(
            'type' => 'yesno'
        )
    ),
    'licence_operating_centre' => array(
        'ad_placed' => array(
            'type' => 'smallint'
        ),
        'sufficient_parking' => array(
            'type' => 'yesno'
        ),
        'permission' => array(
            'type' => 'yesno'
        ),
        'is_interim' => array(
            'type' => 'yesnonull'
        ),
        'publication_appropriate' => array(
            'type' => 'yesnonull'
        ),
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'operatingCentre'
            )
        )
    ),
    'application_operating_centre' => array(
        'ad_placed' => array(
            'type' => 'smallint'
        ),
        'publication_appropriate' => array(
            'type' => 'yesno'
        ),
        'permission' => array(
            'type' => 'yesno'
        ),
        'sufficient_parking' => array(
            'type' => 'yesno'
        ),
        'is_interim' => array(
            'type' => 'yesno'
        ),
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'operatingCentre',
            )
        ),
        'operating_centre_id' => array(
            'inversedBy' => array(
                'entity' => 'OperatingCentre',
                'property' => 'application',
            )
        ),
        's4_id' => array(
            'inversedBy' => array(
                'entity' => 'S4',
                'property' => 'aoc',
            )
        ),
    ),
    'team_printer' => array(
        'team_id' => array(
            'inversedBy' => array(
                'entity' => 'Team',
                'property' => 'teamPrinter',
                'cascade' => array(
                    'persist',
                    'remove'
                ),
                'orphanRemoval' => 'true'
            ),
        ),
        'printer_id' => array(
            'inversedBy' => array(
                'entity' => 'Printer',
                'property' => 'teamPrinter'
            )
        )
    ),
    'task_allocation_rule' => array(
        'team_id' => array(
            'inversedBy' => array(
                'entity' => 'Team',
                'property' => 'taskAllocationRule'
            )
        ),
    ),
    'task_alpha_split' => array(
        'task_allocation_rule_id' => array(
            'inversedBy' => array(
                'entity' => 'TaskAllocationRule',
                'property' => 'taskAlphaSplit'
            )
        ),
    ),
    'document_sub_category' => array(
        'is_scanned' => array(
            'type' => 'yesno'
        ),
        'display_free_text' => array(
            'type' => 'yesno'
        )
    ),
    'cases' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'case'
            )
        ),
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'case'
            )
        ),
        'transport_manager_id' => array(
            'inversedBy' => array(
                'entity' => 'TransportManager',
                'property' => 'case'
            )
        ),
        'is_impounding' => array(
            'type' => 'yesno'
        )
    ),
    'opposition' => array(
        'is_representation' => array(
            'type' => 'yesno'
        ),
        'is_copied' => array(
            'type' => 'yesno'
        ),
        'is_in_time' => array(
            'type' => 'yesno'
        ),
        'is_public_inquiry' => array(
            'type' => 'yesno'
        ),
        'is_withdrawn' => array(
            'type' => 'yesno'
        ),
        'is_willing_to_attend_pi' => array(
            'type' => 'yesno'
        ),
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'opposition'
            )
        ),
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'opposition'
            )
        ),
        'opposer_id' => array(
            'cascade' => array(
                'persist'
            )
        )
    ),
    'operating_centre_opposition' => array(
        'opposition_id' => array(
            'inversedBy' => array(
                'entity' => 'Opposition',
                'property' => 'operatingCentre'
            )
        )
    ),
    'opposer' => array(
        'contact_details_id' => array(
            'cascade' => array(
                'persist'
            )
        )
    ),
    'bus_reg' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'busReg',
                'cascade' => array(
                    'persist'
                )
            )
        ),
        'use_all_stops' => array(
            'type' => 'yesno'
        ),
        'is_short_notice' => array(
            'type' => 'yesno'
        ),
        'has_manoeuvre' => array(
            'type' => 'yesno'
        ),
        'need_new_stop' => array(
            'type' => 'yesno'
        ),
        'has_not_fixed_stop' => array(
            'type' => 'yesno'
        ),
        'timetable_acceptable' => array(
            'type' => 'yesno'
        ),
        'map_supplied' => array(
            'type' => 'yesno'
        ),
        'copied_to_la_pte' => array(
            'type' => 'yesno'
        ),
        'la_short_note' => array(
            'type' => 'yesno'
        ),
        'application_signed' => array(
            'type' => 'yesno'
        ),
        'op_notified_la_pte' => array(
            'type' => 'yesno'
        ),
        'trc_condition_checked' => array(
            'type' => 'yesno'
        ),
        'is_txc_app' => array(
            'type' => 'yesno'
        ),
        'short_notice_refused' => array(
            'type' => 'yesno'
        ),
        'is_quality_partnership' => array(
            'type' => 'yesno'
        ),
        'quality_partnership_facilities_used' => array(
            'type' => 'yesno'
        ),
        'is_quality_contract' => array(
            'type' => 'yesno'
        ),
        'ebsr_refresh' => array(
            'type' => 'yesno'
        )
    ),
    'bus_reg_other_service' => array(
        'bus_reg_id' => array(
            'inversedBy' => array(
                'entity' => 'BusReg',
                'property' => 'otherService',
                'cascade' => array(
                    'persist'
                )
            )
        )
    ),
    'document' => array(
        'document_store_id' => array(
            'property' => 'identifier'
        ),
        'traffic_area_id' => array(
            'inversedBy' => array(
                'entity' => 'TrafficArea',
                'property' => 'document'
            )
        ),
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'document'
            )
        ),
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'document',
                'fetch' => 'EXTRA_LAZY'
            ),
        ),
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'document'
            )
        ),
        'transport_manager_id' => array(
            'inversedBy' => array(
                'entity' => 'TransportManager',
                'property' => 'document'
            )
        ),
        'operating_centre_id' => array(
            'inversedBy' => array(
                'entity' => 'OperatingCentre',
                'property' => 'adDocument'
            )
        ),
        'bus_reg_id' => array(
            'inversedBy' => array(
                'entity' => 'BusReg',
                'property' => 'document'
            )
        ),
        'submission_id' => array(
            'inversedBy' => array(
                'entity' => 'Submission',
                'property' => 'document'
            )
        )
    ),
    'doc_template' => array(
        'is_ni' => array(
            'type' => 'yesno'
        ),
        'suppress_from_op' => array(
            'type' => 'yesno'
        ),
        'document_id' => [
            'inversedBy' => array(
                'entity' => 'Document',
                'property' => 'template'
            )
        ]
    ),
    'doc_template_bookmark' => array(
        'doc_template_id' => array(
            'inversedBy' => array(
                'entity' => 'DocTemplate',
                'property' => 'docTemplateBookmark'
            )
        )
    ),
    'doc_paragraph_bookmark' => array(
        'doc_bookmark_id' => array(
            'inversedBy' => array(
                'entity' => 'DocBookmark',
                'property' => 'docParagraphBookmark'
            )
        )
    ),
    'email' => array(
        'is_sensitive' => array(
            'type' => 'yesnonull'
        )
    ),
    'vehicle' => array(
        'is_articulated' => array(
            'type' => 'yesnonull'
        ),
        'is_refrigerated' => array(
            'type' => 'yesnonull'
        ),
        'is_tipper' => array(
            'type' => 'yesnonull'
        ),
        'is_novelty' => array(
            'type' => 'yesnonull'
        ),
        'section26' => array(
            'type' => 'yesno'
        ),
        'section26_curtail' => array(
            'type' => 'yesno'
        ),
        'section26_revoked' => array(
            'type' => 'yesno'
        ),
        'section26_suspend' => array(
            'type' => 'yesno'
        )
    ),
    'licence_vehicle' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'licenceVehicle'
            )
        ),
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'licenceVehicle'
            )
        ),
        'interim_application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'interimLicenceVehicle'
            )
        ),
        'vehicle_id' => array(
            'inversedBy' => array(
                'entity' => 'Vehicle',
                'property' => 'licenceVehicle'
            ),
            'cascade' => array(
                'persist',
                'remove',
            ),
            // we can't lazy-load this or we get optimistic lock errors on
            // deletion (or cascade remove)
            'fetch' => 'EAGER',
        ),
        'removal' => array(
            'type' => 'yesnonull'
        )
    ),
    'licence_status_rule' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'licenceStatusRule'
            )
        ),
    ),
    'licence_status_decision' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'licenceStatusDecision'
            )
        ),
    ),
    'change_of_entity' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'changeOfEntity'
            )
        ),
    ),
    'goods_disc' => array(
        'is_copy' => array(
            'type' => 'yesno'
        ),
        'is_interim' => array(
            'type' => 'yesno'
        ),
        'is_printing' => array(
            'type' => 'yesno'
        ),
        'requested_by_self_service_user' => array(
            'type' => 'yesno'
        ),
        'reprint_required' => array(
            'type' => 'yesno'
        ),
        'licence_vehicle_id' => array(
            'inversedBy' => array(
                'entity' => 'LicenceVehicle',
                'property' => 'goodsDisc',
                'orderBy' => array(
                    'createdOn' => 'DESC'
                )
            )
        )
    ),
    'psv_disc' => array(
        'is_copy' => array(
            'type' => 'yesnonull'
        ),
        'is_printing' => array(
            'type' => 'yesno'
        ),
        'reprint_required' => array(
            'type' => 'yesnonull'
        ),
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'psvDisc',
                'orderBy' => array(
                    'discNo' => 'ASC'
                )
            )
        )
    ),
    'organisation_person' => array(
        'organisation_id' => array(
            'inversedBy' => array(
                'entity' => 'Organisation',
                'property' => 'organisationPerson'
            )
        ),
        'person_id' => array(
            'inversedBy' => array(
                'entity' => 'Person',
                'property' => 'organisationPerson'
            )
        )
    ),
    'trading_name' => array(
        'organisation_id' => array(
            'inversedBy' => array(
                'entity' => 'Organisation',
                'property' => 'tradingName'
            )
        ),
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'tradingName'
            )
        ),
    ),
    'workshop' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'workshop'
            )
        ),
        'is_external' => array(
            'type' => 'yesno'
        ),
        'maintenance' => array(
            'type' => 'yesno'
        ),
        'safety_inspection' => array(
            'type' => 'yesno'
        ),
    ),
    'stay' => array(
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'stay'
            )
        ),
        'is_tc' => array(
            'type' => 'yesno'
        ),
        'dvsa_notified' => array(
            'type' => 'yesno'
        )
    ),
    'appeal' => array(
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'appeal'
            )
        ),
        'dvsa_notified' => array(
            'type' => 'yesno'
        )
    ),
    'complaint' => array(
        'complainant_contact_details_id' => array(
            'cascade' => array(
                'persist'
            )
        ),
        'driver_id' => array(
            'cascade' => array(
                'persist'
            )
        ),
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'complaint'
            )
        )
    ),
    'complaint_case' => array(
        'complaint_id' => array(
            'cascade' => array(
                'persist',
                'remove'
            )
        ),
        'case_id' => array(
            'cascade' => array(
                'persist'
            ),
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'complaintCase'
            )
        )
    ),
    'prohibition' => array(
        'is_trailer' => array(
            'type' => 'yesnonull'
        ),
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'prohibition'
            )
        ),
    ),
    'prohibition_defect' => array(
        'prohibition_id' => array(
            'inversedBy' => array(
                'entity' => 'Prohibition',
                'property' => 'defect'
            )
        )
    ),
    'conviction' => array(
        'msi' => array(
            'type' => 'yesnonull'
        ),
        'is_declared' => array(
            'type' => 'yesno'
        ),
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'conviction'
            )
        ),
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'conviction'
            )
        ),
        'is_dealt_with' => array(
            'type' => 'yesno'
        )
    ),
    'irfo_gv_permit' => array(
        'is_fee_exempt' => array(
            'type' => 'yesno'
        ),
        'permit_printed' => array(
            'type' => 'yesno'
        )
    ),
    'irfo_psv_auth' => array(
        'is_fee_exempt_application' => array(
            'type' => 'yesno'
        ),
        'is_fee_exempt_annual' => array(
            'type' => 'yesno'
        )
    ),
    'irfo_psv_auth_number' => array(
        'irfo_psv_auth_id' => array(
            'inversedBy' => array(
                'entity' => 'IrfoPsvAuth',
                'property' => 'irfoPsvAuthNumber',
                'cascade' => array(
                    'persist'
                ),
            )
        ),
    ),
    'irfo_partner' => array(
        'organisation_id' => array(
            'inversedBy' => array(
                'entity' => 'Organisation',
                'property' => 'irfoPartner',
                'cascade' => array(
                    'persist'
                ),
            )
        ),
    ),
    'note' => array(
        'priority' => array(
            'type' => 'yesno'
        )
    ),
    'submission' => array(
        'urgent' => array(
            'type' => 'yesnonull'
        )
    ),
    'submission_action' => array(
        'is_decision' => array(
            'type' => 'yesno'
        ),
        'submission_id' => array(
            'inversedBy' => array(
                'entity' => 'Submission',
                'property' => 'submissionAction'
            )
        )
    ),
    'submission_action_type' => array(
        'submission_action_id' => array(
            'inversedBy' => array(
                'entity' => 'SubmissionAction',
                'property' => 'actionType'
            )
        )
    ),
    'submission_section_comment' => array(
        'submission_id' => array(
            'inversedBy' => array(
                'entity' => 'Submission',
                'property' => 'submissionSectionComment'
            )
        )
    ),
    'application_completion' => array(
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'applicationCompletion',
                'cascade' => array(
                    'persist'
                )
            )
        )
    ),
    'application_tracking' => array(
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'applicationTracking',
                'cascade' => array(
                    'persist'
                )
            )
        )
    ),
    'presiding_tc' => array(
        'deleted' => array(
            'type' => 'yesnonull'
        )
    ),
    'condition_undertaking' => array(
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'conditionUndertaking'
            )
        ),
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'conditionUndertaking'
            )
        ),
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'conditionUndertaking'
            )
        ),
        'operating_centre_id' => array(
            'inversedBy' => array(
                'entity' => 'OperatingCentre',
                'property' => 'conditionUndertaking'
            )
        ),
        'is_draft' => array(
            'type' => 'yesno'
        ),
        'is_fulfilled' => array(
            'type' => 'yesno'
        ),
        'is_approved' => array(
            'type' => 'yesno'
        ),
        'lic_condition_variation_id' => array(
            'inversedBy' => array(
                'entity' => 'ConditionUndertaking',
                'property' => 'variationRecord'
            )
        )
    ),
    'organisation_user' => array(
        'user_id' => array(
            'inversedBy' => array(
                'entity' => 'User',
                'property' => 'organisationUser',
                'cascade' => array(
                    'persist'
                ),
                'indexBy' => 'organisation_id',
                'orphanRemoval' => 'true'
            )
        ),
        'organisation_id' => array(
            'inversedBy' => array(
                'entity' => 'Organisation',
                'property' => 'organisationUser'
            )
        ),
        'is_administrator' => array(
            'type' => 'yesno'
        ),
        'sftp_access' => array(
            'type' => 'yesno'
        )
    ),
    'reason' => array(
        'is_decision' => array(
            'type' => 'yesno'
        ),
        'is_read_only' => array(
            'type' => 'yesno'
        ),
        'is_ni' => array(
            'type' => 'yesno'
        ),
        'is_propose_to_revoke' => array(
            'type' => 'yesno'
        )
    ),
    'pi' => array(
        'is_cancelled' => array(
            'type' => 'yesno'
        ),
        'is_adjourned' => array(
            'type' => 'yesno'
        ),
        'licence_revoked_at_pi' => array(
            'type' => 'yesno'
        ),
        'licence_suspended_at_pi' => array(
            'type' => 'yesno'
        ),
        'licence_curtailed_at_pi' => array(
            'type' => 'yesno'
        ),
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'publicInquiry'
            )
        ),
        'tm_called_with_operator' => array(
            'type' => 'yesno'
        ),
    ),
    'legacy_case_action' => array(
        'is_driver' => array(
            'type' => 'yesno'
        )
    ),
    'legacy_recommendation' => array(
        'revoke_lic' => array(
            'type' => 'yesnonull'
        ),
        'status' => array(
            'type' => 'yesnonull'
        )
    ),
    'pi_definition' => array(
        'is_ni' => array(
            'type' => 'yesno'
        )
    ),
    'task' => array(
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'task'
            )
        ),
        'bus_reg_id' => array(
            'inversedBy' => array(
                'entity' => 'BusReg',
                'property' => 'task'
            )
        ),
        'assigned_to_team_id' => array(
            'inversedBy' => array(
                'entity' => 'Team',
                'property' => 'task'
            )
        ),
        'is_closed' => array(
            'type' => 'yesno'
        ),
        'urgent' => array(
            'type' => 'yesno'
        )
    ),
    'inspection_email' => array(
        'processed' => array(
            'type' => 'yesno'
        )
    ),
    'bus_short_notice' => array(
        'bus_reg_id' => array(
            'inversedBy' => array(
                'entity' => 'BusReg',
                'property' => 'shortNotice',
                'cascade' => array(
                    'persist'
                )
            )
        ),
        'bank_holiday_change' => array(
            'type' => 'yesno'
        ),
        'unforseen_change' => array(
            'type' => 'yesno'
        ),
        'timetable_change' => array(
            'type' => 'yesno'
        ),
        'replacement_change' => array(
            'type' => 'yesno'
        ),
        'holiday_change' => array(
            'type' => 'yesno'
        ),
        'trc_change' => array(
            'type' => 'yesno'
        ),
        'police_change' => array(
            'type' => 'yesno'
        ),
        'special_occasion_change' => array(
            'type' => 'yesno'
        ),
        'connection_change' => array(
            'type' => 'yesno'
        ),
        'not_available_change' => array(
            'type' => 'yesno'
        )
    ),
    'recipient' => array(
        'send_app_decision' => array(
            'type' => 'yesno'
        ),
        'send_notices_procs' => array(
            'type' => 'yesno'
        ),
        'is_police' => array(
            'type' => 'yesno'
        ),
        'is_objector' => array(
            'type' => 'yesno'
        )
    ),
    'fee_type' => array(
        'expire_fee_with_licence' => array(
            'type' => 'yesno'
        ),
        'is_ni' => array(
            'type' => 'yesno'
        ),
    ),
    'waive_reason' => array(
        'is_irfo' => array(
            'type' => 'yesno'
        )
    ),
    'fee' => array(
        'irfo_fee_exempt' => array(
            'type' => 'yesnonull'
        ),
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'fee'
            )
        ),
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'fee',
            ),
        ),
        'bus_reg_id' => array(
            'inversedBy' => array(
                'entity' => 'BusReg',
                'property' => 'fee',
            ),
        ),
        'ecmt_permit_application_id' => array(
            'inversedBy' => array(
                'entity' => 'EcmtPermitApplication',
                'property' => 'fee'
            )
        ),
        'irhp_application_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpApplication',
                'property' => 'fee'
            )
        ),
    ),
    'ebsr_submission_result' => array(
        'email_authority' => array(
            'type' => 'yesno'
        )
    ),
    'ebsr_submission' => array(
        'is_from_ftp' => array(
            'type' => 'yesno'
        ),
        'bus_reg_id' => array(
            'inversedBy' => array(
                'entity' => 'BusReg',
                'property' => 'ebsrSubmission'
            )
        ),
        'document_id' => array(
            'inversedBy' => array(
                'entity' => 'Document',
                'property' => 'ebsrSubmission',
                'cascade' => array(
                    'persist'
                )
            )
        )
    ),
    'alpha_split' => array(
        'is_deleted' => array(
            'type' => 'yesno'
        )
    ),
    'application_action_ref' => array(
        'default_received' => array(
            'type' => 'yesnonull'
        ),
        'default_approved' => array(
            'type' => 'yesnonull'
        )
    ),
    'application_action' => array(
        'is_received' => array(
            'type' => 'yesnonull'
        ),
        'is_approved' => array(
            'type' => 'yesnonull'
        ),
        'is_applicable' => array(
            'type' => 'yesnonull'
        )
    ),
    'erru_request' => array(
        'response_sent' => array(
            'type' => 'yesno'
        ),
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'erruRequest',
                'cascade' => array(
                    'persist'
                )
            )
        ),
        'request_document_id' => array(
            'inversedBy' => array(
                'entity' => 'Document',
                'property' => 'requestErru',
                'cascade' => array(
                    'persist'
                )
            )
        ),
        'response_document_id' => array(
            'inversedBy' => array(
                'entity' => 'Document',
                'property' => 'responseErru',
                'cascade' => array(
                    'persist'
                )
            )
        )
    ),
    'serious_infringement' => array(
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'seriousInfringement',
                'cascade' => array(
                    'persist'
                )
            )
        )
    ),
    'si_penalty' => array(
        'imposed' => array(
            'type' => 'yesnonull'
        ),
        'serious_infringement_id' => array(
            'inversedBy' => array(
                'entity' => 'SeriousInfringement',
                'property' => 'appliedPenaltie'
            )
        )
    ),
    'si_penalty_erru_imposed' => array(
        'serious_infringement_id' => array(
            'inversedBy' => array(
                'entity' => 'SeriousInfringement',
                'property' => 'imposedErru',
                'cascade' => array(
                    'persist'
                )
            )
        )
    ),
    'si_penalty_erru_requested' => array(
        'serious_infringement_id' => array(
            'inversedBy' => array(
                'entity' => 'SeriousInfringement',
                'property' => 'requestedErru',
                'cascade' => array(
                    'persist'
                )
            )
        )
    ),
    'correspondence_inbox' => array(
        'archived' => array(
            'type' => 'yesno'
        ),
        'accessed' => array(
            'type' => 'yesno'
        ),
        'email_reminder_sent' => array(
            'type' => 'yesno'
        ),
        'printed' => array(
            'type' => 'yesno'
        )
    ),
    'disc_sequence' => array(
        'is_self_serve' => array(
            'type' => 'yesno'
        ),
        'is_ni_self_serve' => array(
            'type' => 'yesno'
        )
    ),
    'disqualification' => array(
        'is_disqualified' => array(
            'type' => 'yesnonull'
        ),
        'organisation_id' => array(
            'inversedBy' => array(
                'entity' => 'Organisation',
                'property' => 'disqualification'
            )
        ),
        'person_id' => array(
            'inversedBy' => array(
                'entity' => 'Person',
                'property' => 'disqualification'
            )
        ),
    ),
    'legacy_offence' => array(
        'is_trailer' => array(
            'type' => 'yesnonull'
        ),
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'legacyOffence'
            )
        )
    ),
    'community_lic_suspension' => array(
        'is_actioned' => array(
            'type' => 'yesnonull'
        ),
        'community_lic_id' => array(
            'inversedBy' => array(
                'entity' => 'CommunityLic',
                'property' => 'communityLicSuspension'
            ),
            'cascade' => array(
                'persist'
            )
        ),
    ),
    'community_lic_withdrawal' => array(
        'community_lic_id' => array(
            'inversedBy' => array(
                'entity' => 'CommunityLic',
                'property' => 'communityLicWithdrawal'
            ),
            'cascade' => array(
                'persist'
            )
        ),
    ),
    'community_lic_suspension_reason' => array(
        'community_lic_suspension_id' => array(
            'inversedBy' => array(
                'entity' => 'CommunityLicSuspension',
                'property' => 'communityLicSuspensionReason'
            ),
            'cascade' => array(
                'persist'
            )
        ),
    ),
    'irfo_vehicle' => array(
        'coc_a' => array(
            'type' => 'yesno'
        ),
        'coc_b' => array(
            'type' => 'yesno'
        ),
        'coc_c' => array(
            'type' => 'yesno'
        ),
        'coc_d' => array(
            'type' => 'yesno'
        ),
        'coc_t' => array(
            'type' => 'yesno'
        )
    ),
    'system_info_message' => array(
        'is_internal' => array(
            'type' => 'yesno'
        ),
        'is_deleted' => array(
            'type' => 'yesno'
        )
    ),
    'opposition_grounds' => array(
        'opposition_id' => array(
            'inversedBy' => array(
                'entity' => 'Opposition',
                'property' => 'ground'
            )
        )
    ),
    'tm_case_decision' => array(
        'is_msi' => array(
            'type' => 'yesno'
        ),
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'tmDecision'
            )
        ),
    ),
    'tm_grace_period' => array(
        'is_active' => array(
            'type' => 'yesno'
        )
    ),
    'txc_inbox' => array(
        'file_read' => array(
            'type' => 'yesnonull'
        ),
        'bus_reg_id' => array(
            'inversedBy' => array(
                'entity' => 'BusReg',
                'property' => 'txcInbox',
                'cascade' => array(
                    'persist'
                )
            )
        ),
    ),
    'public_holiday' => array(
        'is_england' => array(
            'type' => 'yesnonull'
        ),
        'is_wales' => array(
            'type' => 'yesnonull'
        ),
        'is_scotland' => array(
            'type' => 'yesnonull'
        ),
        'is_ni' => array(
            'type' => 'yesnonull'
        )
    ),
    'driver' => array(
        'contact_details_id' => array(
            'cascade' => array(
                'persist'
            )
        )
    ),
    'pi_hearing' => array(
        'is_adjourned' => array(
            'type' => 'yesno'
        ),
        'pi_id' => array(
            'inversedBy' => array(
                'entity' => 'Pi',
                'property' => 'piHearing'
            )
        ),
        'is_cancelled' => array(
            'type' => 'yesno'
        ),
        'is_full_day' => array(
            'type' => 'yesnonull'
        ),
    ),
    'pi_reason' => array(
        'pi_id' => array(
            'inversedBy' => array(
                'entity' => 'Pi',
                'property' => 'piReason'
            )
        )
    ),
    /* 'pi_type' => array(
      'pi_id' => array(
      'inversedBy' => array(
      'entity' => 'Pi',
      'property' => 'piType'
      )
      )
      ) , */
    'category' => array(
        'is_doc_category' => array(
            'type' => 'yesno'
        ),
        'is_task_category' => array(
            'type' => 'yesno'
        )
    ),
    'task_sub_category' => array(
        'is_freetext_description' => array(
            'type' => 'yesno'
        )
    ),
    'ref_data' => array(
        '@settings' => array(
            'repository' => 'Dvsa\Olcs\Api\Domain\Repository\RefData'
        ),
        'description' => array(
            'translatable' => true
        )
    ),
    'ext_translations' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'phone_contact' => array(
        'contact_details_id' => array(
            'inversedBy' => array(
                'entity' => 'ContactDetails',
                'property' => 'phoneContact',
                'cascade' => array(
                    'persist'
                ),
                'indexBy' => 'id',
                'orphanRemoval' => 'true',
                'orderBy' => array(
                    'id' => 'DESC',
                ),
            )
        )
    ),
    'previous_conviction' => array(
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'previousConviction'
            )
        ),
        'transport_manager_id' => array(
            'inversedBy' => array(
                'entity' => 'TransportManager',
                'property' => 'previousConviction'
            )
        )
    ),
    'private_hire_licence' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'privateHireLicence'
            )
        )
    ),
    'fee_txn' => array(
        'fee_id' => array(
            'inversedBy' => array(
                'entity' => 'Fee',
                'property' => 'feeTransaction',
                'cascade' => array(
                    'persist'
                ),
            ),
            'cascade' => array(
                'persist'
            ),
        ),
        'txn_id' => array(
            'inversedBy' => array(
                'entity' => 'Transaction',
                'property' => 'feeTransaction',
                'cascade' => array(
                    'persist'
                ),
            ),
            'cascade' => array(
                'persist'
            ),
        ),
        'reversed_fee_txn_id' =>  array(
            'inversedBy' => array(
                'entity' => 'FeeTransaction',
                'property' => 'reversingFeeTransaction',
            ),
        ),
    ),
    'transport_manager_licence' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'tmLicence'
            ),
        ),
        'transport_manager_id' => array(
            'inversedBy' => array(
                'entity' => 'TransportManager',
                'property' => 'tmLicence'
            ),
        ),
        'is_owner' => array(
            'type' => 'yesnonull'
        )
    ),
    'tm_qualification' => array(
        'transport_manager_id' => array(
            'inversedBy' => array(
                'entity' => 'TransportManager',
                'property' => 'qualification'
            ),
        )
    ),
    'tm_employment' => array(
        'transport_manager_id' => array(
            'inversedBy' => array(
                'entity' => 'TransportManager',
                'property' => 'employment'
            ),
        )
    ),
    'other_licence' => array(
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'otherLicence'
            )
        ),
        'will_surrender' => array(
            'type' => 'yesnonull'
        ),
        'transport_manager_licence_id' => array(
            'inversedBy' => array(
                'entity' => 'TransportManagerLicence',
                'property' => 'otherLicence'
            ),
        ),
        'transport_manager_application_id' => array(
            'inversedBy' => array(
                'entity' => 'TransportManagerApplication',
                'property' => 'otherLicence'
            ),
        ),
        'transport_manager_id' => array(
            'inversedBy' => array(
                'entity' => 'TransportManager',
                'property' => 'otherLicence'
            ),
        )
    ),
    'publication_link' => array(
        'pi_id' => array(
            'inversedBy' => array(
                'entity' => 'Pi',
                'property' => 'publicationLink'
            )
        ),
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'publicationLink'
            )
        ),
        'publication_id' => array(
            'inversedBy' => array(
                'entity' => 'Publication',
                'property' => 'publicationLink'
            )
        ),
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'publicationLink'
            )
        ),
        'bus_reg_id' => array(
            'inversedBy' => array(
                'entity' => 'BusReg',
                'property' => 'publicationLink'
            )
        ),
    ),
    'publication_police_data' => array(
        'publication_link_id' => array(
            'inversedBy' => array(
                'entity' => 'PublicationLink',
                'property' => 'policeData',
                'cascade' => array(
                    'persist',
                ),
                'orphanRemoval' => array(
                    'true',
                ),
            )
        )
    ),
    'role_permission' => array(
        'role_id' => array(
            'inversedBy' => array(
                'entity' => 'Role',
                'property' => 'rolePermission'
            )
        )
    ),
    'transport_manager_application' => array(
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'transportManager',
                'cascade' => array(
                    'remove',
                )
            ),
        ),
        'transport_manager_id' => array(
            'inversedBy' => array(
                'entity' => 'TransportManager',
                'property' => 'tmApplication'
            ),
        ),
        'is_owner' => array(
            'type' => 'yesnonull'
        ),
        'declaration_confirmation' => array(
            'type' => 'yesno'
        ),
    ),
    'statement' => array(
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'statement'
            ),
        ),
        'requestors_contact_details_id' => array(
            'cascade' => array(
                'persist'
            )
        )
    ),
    'community_lic' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'communityLic',
                'fetch' => 'EXTRA_LAZY'
            )
        ),
    ),
    'company_subsidiary' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'companySubsidiarie'
            )
        )
    ),
    'application_organisation_person' => array(
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'applicationOrganisationPerson'
            )
        ),
        'person_id' => array(
            'inversedBy' => array(
                'entity' => 'Person',
                'property' => 'applicationOrganisationPerson'
            )
        )
    ),
    'continuation_detail' => array(
        'received' => array(
            'type' => 'yesno'
        ),
        'checklist_document_id' => array(
            'inversedBy' => array(
                'entity' => 'Document',
                'property' => 'continuationDetail'
            )
        ),
        'has_overdraft' => array(
            'type' => 'yesnonull'
        ),
        'has_other_finances' => array(
            'type' => 'yesnonull'
        ),
        'has_factoring' => array(
            'type' => 'yesnonull'
        ),
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'continuationDetail'
            )
        ),
    ),
    'companies_house_officer' => array(
        'companies_house_company_id' => array(
            'inversedBy' => array(
                'entity' => 'CompaniesHouseCompany',
                'property' => 'officer',
                'cascade' => array(
                    'persist',
                ),
            ),
        ),
    ),
    'companies_house_alert_reason' => array(
        'companies_house_alert_id' => array(
            'inversedBy' => array(
                'entity' => 'CompaniesHouseAlert',
                'property' => 'reason',
                'cascade' => array(
                    'persist',
                ),
            ),
        ),
    ),
    'companies_house_alert' => array(
        'is_closed' => array(
            'type' => 'yesno'
        ),
    ),
    'grace_period' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'gracePeriod'
            )
        ),
    ),
    'traffic_area_enforcement_area' => array(
        'traffic_area_id' => array(
            'inversedBy' => array(
                'entity' => 'TrafficArea',
                'property' => 'trafficAreaEnforcementArea'
            )
        )
    ),
    'transport_manager' => array(
        'merge_details' => array(
            'type' => 'json_array'
        ),
    ),
    'application_read_audit' => array(
        'application_id' => array(
            'inversedBy' => array(
                'entity' => 'Application',
                'property' => 'readAudit'
            )
        )
    ),
    'licence_read_audit' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'readAudit'
            )
        )
    ),
    'bus_reg_read_audit' => array(
        'bus_reg_id' => array(
            'inversedBy' => array(
                'entity' => 'BusReg',
                'property' => 'readAudit'
            )
        )
    ),
    'transport_manager_read_audit' => array(
        'transport_manager_id' => array(
            'inversedBy' => array(
                'entity' => 'TransportManager',
                'property' => 'readAudit'
            )
        )
    ),
    'cases_read_audit' => array(
        'case_id' => array(
            'inversedBy' => array(
                'entity' => 'Cases',
                'property' => 'readAudit'
            )
        )
    ),
    'organisation_read_audit' => array(
        'organisation_id' => array(
            'inversedBy' => array(
                'entity' => 'Organisation',
                'property' => 'readAudit'
            )
        )
    ),
    'task_search_view' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'document_search_view' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'bus_reg_browse_view' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'bus_reg_search_view' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'vi_vhl_vw' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'vi_tnm_vw' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'vi_oc_vw' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'vi_op_vw' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'vehicle_history_view' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'bus_reg_history_view' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'other_service_view' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'vi_oc_view' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'vi_op_view' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'vi_tnm_view' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'vi_vhl_view' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'historic_tm' => array(
        'seen_contract' => array(
            'type' => 'yesno'
        ),
        'seen_qualification' => array(
            'type' => 'yesno'
        )
    ),
    'sla_target_date' => array(
        'document_id' => array(
            'inversedBy' => array(
                'entity' => 'Document',
                'property' => 'slaTargetDate',
                'cascade' => array(
                    'persist'
                )
            )
        ),
        'pi_id' => array(
            'inversedBy' => array(
                'entity' => 'Pi',
                'property' => 'slaTargetDate',
                'cascade' => array(
                    'persist'
                ),
                'indexBy' => 'sla_id',
                'orphanRemoval' => 'true'
            )
        ),
        'submission_id' => array(
            'inversedBy' => array(
                'entity' => 'Submission',
                'property' => 'slaTargetDate',
                'cascade' => array(
                    'persist'
                ),
                'indexBy' => 'sla_id',
                'orphanRemoval' => 'true'
            )
        ),
        'propose_to_revoke_id' => array(
            'inversedBy' => array(
                'entity' => 'ProposeToRevoke',
                'property' => 'slaTargetDate',
                'cascade' => array(
                    'persist'
                ),
                'indexBy' => 'sla_id',
                'orphanRemoval' => 'true'
            )
        ),
        'statement_id' => array(
            'inversedBy' => array(
                'entity' => 'Statement',
                'property' => 'slaTargetDate',
                'cascade' => array(
                    'persist'
                ),
                'indexBy' => 'sla_id',
                'orphanRemoval' => 'true'
            )
        ),
        'under_delegation' => array(
            'type' => 'yesno'
        ),
    ),
    'digital_signature' => array(
        'attributes' => array(
            'type' => 'encrypted_string'
        ),
    ),
    'ecmt_permit_application' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'ecmtApplication'
            )
        ),
    ),
    'irhp_application' => array(
        'licence_id' => array(
            'inversedBy' => array(
                'entity' => 'Licence',
                'property' => 'irhpApplication'
            )
        ),
    ),
    'irhp_application_view' => array(
        '@settings' => array(
            'ignore' => true
        )
    ),
    'irhp_candidate_permit' => array(
        'irhp_permit_application_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpPermitApplication',
                'property' => 'irhpCandidatePermit'
            )
        ),
        'irhp_permit_range_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpPermitRange',
                'property' => 'irhpCandidatePermit'
            )
        )
    ),
    'irhp_permit_application' => array(
        'ecmt_permit_application_id' => array(
            'inversedBy' => array(
                'entity' => 'EcmtPermitApplication',
                'property' => 'irhpPermitApplication'
            )
        ),
        'irhp_application_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpApplication',
                'property' => 'irhpPermitApplication'
            )
        ),
    ),
    'irhp_permit' => array(
        'irhp_permit_application_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpPermitApplication',
                'property' => 'irhpPermit'
            )
        ),
        'irhp_candidate_permit_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpCandidatePermit',
                'property' => 'irhpPermit'
            )
        ),
        'irhp_permit_range_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpPermitRange',
                'property' => 'irhpPermit'
            )
        ),
    ),
    'irhp_permit_range' => array(
        'irhp_permit_stock_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpPermitStock',
                'property' => 'irhpPermitRange'
            )
        )
    ),
    'irhp_permit_stock' => array(
        'irhp_permit_type_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpPermitType',
                'property' => 'irhpPermitStock'
            )
        ),
        'country_id' => array(
            'inversedBy' => array(
                'entity' => 'Country',
                'property' => 'irhpPermitStock'
            )
        )
    ),
    'irhp_permit_window' => array(
        'irhp_permit_stock_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpPermitStock',
                'property' => 'irhpPermitWindow'
            )
        )
    ),
    'irhp_permit_sector_quota' => array(
        'irhp_permit_stock_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpPermitStock',
                'property' => 'irhpPermitSectorQuota'
            )
        )
    ),
    'irhp_permit_jurisdiction_quota' => array(
        'irhp_permit_stock_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpPermitStock',
                'property' => 'irhpPermitJurisdictionQuota'
            )
        )
    ),
    'question_text' => array(
        'question_id' => array(
            'inversedBy' => array(
                'entity' => 'Question',
                'property' => 'questionText'
            )
        ),
    ),
    'application_path' => array(
        'irhp_permit_type_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpPermitType',
                'property' => 'applicationPath'
            )
        ),
    ),
    'application_step' => array(
        'application_path_id' => array(
            'inversedBy' => array(
                'entity' => 'ApplicationPath',
                'property' => 'applicationStep',
                'orderBy' => array(
                    'weight' => 'ASC'
                )
            )
        ),
    ),
    'application_validation' => array(
        'question_id' => array(
            'inversedBy' => array(
                'entity' => 'Question',
                'property' => 'applicationValidation'
            )
        ),
        'application_step_id' => array(
            'inversedBy' => array(
                'entity' => 'ApplicationStep',
                'property' => 'applicationValidation'
            )
        ),
    ),
    'answer' => array(
        'irhp_application_id' => array(
            'inversedBy' => array(
                'entity' => 'IrhpApplication',
                'property' => 'answer',
                'indexBy' => 'question_text_id',
            )
        ),
    ),
);
