Thank you for your EBSR application received on <?php echo $this->submissionDate; ?> for the following local bus service - <?php echo $this->registrationNumber; ?> - between <?php echo $this->origin; ?> and <?php echo $this->destination; ?> with service number <?php echo $this->lineName; ?> to come into effect on <?php echo $this->startDate; ?>.

A new version of the <?php echo $this->pdfType; ?> is now available for this registration. Please log on to view this if required.

Please do not reply directly to this e-mail by using the ‘reply’ function in your e-mail package as this is an automated facility that cannot handle incoming e-mails. If you need to contact us, please ring your usual caseworker or e-mail: notifications@vehicle-operator-licensing.service.gov.uk