Hello,

<?php echo $this->organisation ?> has named you as a Transport Manager on Vehicle Operator Licence application <?php echo $this->reference ?>.

Before we can consider the application, you’ll need to submit your details to us through our online service.

Your username is: <?php echo $this->loginId ?>

You’ll receive a second email with a temporary password in the next two hours. If it doesn’t arrive email notifications@vehicle-operator-licensing.service.gov.uk.

Sign in at <?php echo $this->url; ?>