<?php $title = 'Application for ' . $data['permitType'] . ' Permit'; ?>
<!DOCTYPE html>
<html lang="en">

<head>

    <title><?php echo $title; ?></title>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="/styles/print.css" media="screen, print" rel="stylesheet" type="text/css">

</head>

<body>

    <div class="printable">

        <div class="printable__header">
            <h1><?php echo $title; ?></h1>
            <h2><?php echo $data['operator']; ?> <?php echo $data['ref']; ?></h2>
            <a class="hide-print" href="javascript:window.print()">Print this page</a>
        </div>

        <div class="printable__section">
            <dl>
                <dt>Licence selected</dt>
                <dd><?php echo $data['licence']; ?></dd>

                <dt>I confirm that my ECMT permits will only be used by vehicles that are environmentally compliant with Euro 6 emissions standards.</dt>
                <dd><?php echo $data['emissions']; ?></dd>

                <dt>I confirm that I will not undertake any cabotage journeys using an ECMT permit.</dt>
                <dd><?php echo $data['cabotage']; ?></dd>

                <dt>In the next 12 months are you transporting goods to Austria, Greece, Hungary, Italy or Russia?</dt>
                <dd><?php echo $data['limited-permits']; ?></dd>

                <dt>How many permits do you require for this licence?</dt>
                <dd><?php echo $data['number-required']; ?></dd>

                <dt>How many international trips did you make in the last 12 months using this licence?</dt>
                <dd><?php echo $data['trips']; ?></dd>

                <dt>In the last 12 months, what percentage of international trips did you make using this licence?</dt>
                <dd><?php echo $data['int-journeys']; ?></dd>

                <dt>Select one sector you mainly transport goods in using this licence</dt>
                <dd><?php echo $data['goods']; ?></dd>
            </dl>
        </div>

        <div class="printable__section">
            <ul>
                <li>I have read the Guidance Notes (https://www.gov.uk/guidance/international-authorisations-and-permits-for-road-haulage) on how to use ECMT permits.</li>
                <li>I understand if a permit is issued it may exclude travel to Austria, Greece, Hungary, Italy and Russia as there are limited numbers of permits for travel to these countries.</li>
                <li>I understand that if a permit is issued I will be issued with a corresponding logbook which I must complete with full journey details before the start of a journey.</li>
                <li>I understand that I must carry a permit and corresponding logbook for the entire outbound and return journey.</li>
                <li>I declare that the statements and information provided are true and that my application is correct. I understand that it is an offence to make a false declaration to obtain a permit.</li>
            </ul>
        </div>

        <div class="signature-box">
            <div class="signature-box__column">
                <label for="" class="signature-box__label">Applicant's signature</label>
                <input type="text" class="signature-box__input signature" disabled="disabled">
                <label for="" class="signature-box__label">Full name in block capitals</label>
                <input type="text" class="signature-box__input name" disabled="disabled">
                <label for="" class="signature-box__label">Position in Company</label>
                <input type="text" class="signature-box__input position" disabled="disabled">
                <label for="" class="signature-box__label">Date</label>
                <input type="text" class="signature-box__input date" disabled="disabled">
            </div>
        </div>

        <div class="printable__address">
            <p><b>Return to:</b></p>
            <p>International Road Haulage Permit Office, Hillcrest House, 386 Harehills Lane, Leeds, LS9 6NF</p>
        </div>
    </div>

</body>
</html>
