    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle($this->translate(''));
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headLink()
            ->appendStylesheet(
                '//olcs-static/styles/selfserve.css',
                'screen, print'
            );
        echo $this->headScript();
        ?>
    </head>