<head>
    
    <meta charset="utf-8">
    
    <?php
        echo $this->headTitle($this->translate(''));
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headScript();
    ?>

    <style>

        body {
            font-family: Arial, sans-serif;
            background: #FFF;
            margin: 0 auto;
            max-width: 860px;
            padding: 0 20px;
            font-size: 15px;
            line-height: 1.4;
            padding-bottom: 50px;
        }

        h3,
        h4 {
            font-size: 20px;
            width: 100%;
            float: left;
            display: block;
            margin: 0;
        }

        h4 {
            font-size: 17px;
        }

        p {
            max-width: 700px;
            margin-bottom: .6em;
        }

        ul {
            list-style: none;
            margin: 0;
            padding: 0;
        }

        dt,
        dd {
            float: left;
            overflow: auto;
            margin: 0;
            padding: 0 2.5% 10px 0;
            width: 47.5%;
        }

        dd {
            font-weight: 600;
        }

        hr {
            float: left;
            margin: 15px 0;
            border: 0;
            height: 1px;
            width: 100%;
            background: #dee0e2;
        }

        .review-header {
            padding: 100px 0 50px 0;
            width: 70%;
        }

        .review-header h1 {
            font-size: 44px;
        }

        .review-header p {
            font-size: 19px;
        }

        .review-section {
            border-top: 3px solid #000;
            padding-top: 20px;
            margin-bottom: 20px;
            float: left;
            width: 100%;
        }

        .review-section h2 {
            font-size: 30px;
            margin: 0 0 40px 0;
        }

        .read-only__header {
            border-bottom: 1px solid #dee0e2;
            margin-bottom: 1em;
            float: left;
            width: 100%;
            padding-bottom: 8px;
        }


        .definition-list {
            float: left;
            border-bottom: 1px solid #DEE0E6;
            margin: 0 0 12px;
            padding: 0 0 3px;
            width: 100%;
        }

        .definition-list__item {
            width: 100%;
            float: left;
        }

        .definition-list:last-child {
            border-bottom: 0;
        }
        
        @media print {
            .hide-print {
                display: none;
            }
        }

        /**
         * Need to check these styles with Sam
         */
        ul.bullet {
            list-style: disc;
            margin: 10px;
            padding: 10px;
        }

        form .field {
            margin-bottom: 10px;
            clear: both;
        }

        form .field.inline-70 {
            float: left;
            width: 70%;
        }

        form .field.inline-30 {
            float: left;
            width: 30%;
            clear: none;
        }

        form .field label {
            display: block;
            padding-top: 10px;
            padding-bottom: 10px;
        }

        form input[type="text"] {
            display: block;
            padding: 10px;
            width: 100%;
        }

        form .field.inline-70 input[type="text"] {
            width: 90%
        }

        form label.inline {
            float: left;
            padding: 10px;
        }

        .signature-box {
            margin: 30px 0;
            padding: 30px 0 30px 5%;
            background: #dee0e2;
            overflow: auto;
            -webkit-print-color-adjust: exact;
        }

        .signature-box__column {
            float: left;
            width: 45%;
            margin: 0 5% 0 0;
        }

        .signature-box__label {
            font-weight: 600;
        }

        .signature-box__input {
            width: 100%;
            border: 2px solid #0b0c0c;
            margin-bottom: 20px;
        }

        .signature-box__input.signature {
            height: 100px;
        }

        .signature-box__input.date {
            width: 200px;
        }
        
    </style>
    
</head>