<?php

namespace Dvsa\Olcs\Api\Service\Submission\Sections;

use Laminas\ServiceManager\AbstractPluginManager;

class SectionGeneratorPluginManager extends AbstractPluginManager
{
    protected $instanceOf = SectionGeneratorInterface::class;

    protected $aliases = [
        'case-summary' => CaseSummary::class,
        'case-outline' => CaseOutline::class,
        'most-serious-infringement' => MostSeriousInfringement::class,
        'outstanding-applications' => OutstandingApplications::class,
        'people' => People::class,
        'operating-centres' => OperatingCentres::class,
        'conditions-and-undertakings' => ConditionsAndUndertakings::class,
        'intelligence-unit-check' => NoDataCommentsOnly::class,
        'interim' => NoDataCommentsOnly::class,
        'advertisement' => NoDataCommentsOnly::class,
        'linked-licences-app-numbers' => LinkedLicences::class,
        'lead-tc-area' => LeadTcArea::class,
        'current-submissions' => NoDataCommentsOnly::class,
        'auth-requested-applied-for' => AuthRequestedAppliedFor::class,
        'transport-managers' => TransportManagers::class,
        'continuous-effective-control' => NoDataCommentsOnly::class,
        'fitness-and-repute' => NoDataCommentsOnly::class,
        'previous-history' => NoDataCommentsOnly::class,
        'bus-reg-app-details' => NoDataCommentsOnly::class,
        'transport-authority-comments' => NoDataCommentsOnly::class,
        'total-bus-registrations' => NoDataCommentsOnly::class,
        'local-licence-history' => NoDataCommentsOnly::class,
        'linked-mlh-history' => NoDataCommentsOnly::class,
        'registration-details' => NoDataCommentsOnly::class,
        'maintenance-tachographs-hours' => NoDataCommentsOnly::class,
        'prohibition-history' => ProhibitionHistory::class,
        'conviction-fpn-offence-history' => ConvictionFpnOffenceHistory::class,
        'annual-test-history' => AnnualTestHistory::class,
        'penalties' => Penalties::class,
        'other-issues' => NoDataCommentsOnly::class,
        'te-reports' => NoDataCommentsOnly::class,
        'site-plans' => NoDataCommentsOnly::class,
        'planning-permission' => NoDataCommentsOnly::class,
        'applicants-comments' => ApplicantsComments::class,
        'applicants-responses' => ApplicantsResponses::class,
        'visibility-access-egress-size' => NoDataCommentsOnly::class,
        'compliance-complaints' => ComplianceComplaints::class,
        'environmental-complaints' => EnvironmentalComplaints::class,
        'oppositions' => Oppositions::class,
        'financial-information' => NoDataCommentsOnly::class,
        'maps' => NoDataCommentsOnly::class,
        'waive-fee-late-fee' => NoDataCommentsOnly::class,
        'surrender' => NoDataCommentsOnly::class,
        'annex' => NoDataCommentsOnly::class,
        'statements' => Statements::class,
        'tm-details' => TmDetails::class,
        'tm-responsibilities' => TmResponsibilities::class,
        'tm-qualifications' => TmQualifications::class,
        'tm-other-employment' => TmOtherEmployment::class,
        'tm-previous-history' => TmPreviousHistory::class,
    ];

    protected $factories = [
        // ZF2.5
        'dvsaolcsapiservicesubmissionsectionscasesummary' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionscaseoutline' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsmostseriousinfringement' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsoutstandingapplications' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionspeople' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsoperatingcentres' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsconditionsandundertakings' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsnodatacommentsonly' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionslinkedlicences' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsleadtcarea' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsauthrequestedappliedfor' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionstransportmanagers' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsprohibitionhistory' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsconvictionfpnoffencehistory' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsannualtesthistory' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionspenalties' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsstatements' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsenvironmentalcomplaints' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionscompliancecomplaints' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsoppositions' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionstmdetails' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionstmresponsibilities' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionstmqualifications' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionstmotheremployment' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionstmprevioushistory' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsapplicantscomments' => AbstractFactory::class,
        'dvsaolcsapiservicesubmissionsectionsapplicantsresponses' => AbstractFactory::class,

        // ZF3.0
        CaseSummary::class => AbstractFactory::class,
        CaseOutline::class => AbstractFactory::class,
        MostSeriousInfringement::class => AbstractFactory::class,
        OutstandingApplications::class => AbstractFactory::class,
        People::class => AbstractFactory::class,
        OperatingCentres::class => AbstractFactory::class,
        ConditionsAndUndertakings::class => AbstractFactory::class,
        NoDataCommentsOnly::class => AbstractFactory::class,
        LinkedLicences::class => AbstractFactory::class,
        LeadTcArea::class => AbstractFactory::class,
        AuthRequestedAppliedFor::class => AbstractFactory::class,
        TransportManagers::class => AbstractFactory::class,
        ProhibitionHistory::class => AbstractFactory::class,
        ConvictionFpnOffenceHistory::class => AbstractFactory::class,
        AnnualTestHistory::class => AbstractFactory::class,
        Penalties::class => AbstractFactory::class,
        Statements::class => AbstractFactory::class,
        EnvironmentalComplaints::class => AbstractFactory::class,
        ComplianceComplaints::class => AbstractFactory::class,
        Oppositions::class => AbstractFactory::class,
        TmDetails::class => AbstractFactory::class,
        TmResponsibilities::class => AbstractFactory::class,
        TmQualifications::class => AbstractFactory::class,
        TmOtherEmployment::class => AbstractFactory::class,
        TmPreviousHistory::class => AbstractFactory::class,
        ApplicantsComments::class => AbstractFactory::class,
        ApplicantsResponses::class => AbstractFactory::class,
    ];
}
