Thank you for your EBSR Data Refresh submission received on <?php echo $this->submissionDate ?> for the following local bus service - <?php echo $this->registrationNumber; ?> - between <?php echo $this->origin; ?> and <?php echo $this->destination; ?> with service number <?php echo $this->lineName; ?> to come into effect on <?php echo $this->startDate; ?>.

Your submission has been accepted and our existing manual records have now been updated with the Electronic Bus Service Registration (EBSR) file.

We have copied this e-mail to the following local authorities: <?php echo $this->localAuthoritys; ?>.

You will find a copy of the PDF version of the registered particulars in your document area. Please check the contents and let us know if there are any discrepancies so we can correct them as quickly as possible.