Thank you for your EBSR application received on <?php echo $this->submissionDate ?> for the following local bus service - <?php echo $this->registrationNumber; ?> - between <?php echo $this->origin; ?> and <?php echo $this->destination; ?> with service number <?php echo $this->lineName; ?> came into effect on <?php echo $this->startDate; ?>.

We would remind you that you must continue to operate the service until the cancellation date mentioned above. If you do not, you could face disciplinary action by the Traffic Commissioner.

Notice of this cancellation application will appear in "Notices and Proceedings" issue number <?php echo $this->publicationId; ?>. We have copied this e-mail to the following local authorities: <?php echo $this->localAuthoritys; ?>.