Thank you for your EBSR application received on <?php echo $this->submissionDate ?> for the following local bus service - <?php echo $this->registrationNumber; ?> - between <?php echo $this->origin; ?> and <?php echo $this->destination; ?> with service number <?php echo $this->lineName; ?> to come into effect on <?php echo $this->startDate; ?>.

Your application has been accepted. However you must not start or change your service until the date mentioned above. If you do, you could face disciplinary action by the Traffic Commissioner.

Notice of this application will appear in "Notices and Proceedings" issue number <?php echo $this->publicationId; ?>. We have copied this e-mail to the following local authorities: <?php echo $this->localAuthoritys; ?>.

You will find a copy of the PDF version of the registered particulars in your document area. Please check the contents and let us know if there are any discrepancies so we can sort them out as quickly as possible.