Your ECMT permit application <?php echo $this->escapeHtml($this->applicationRef); ?> has now been considered and processed.

Application status: Unsucccessful

Unfortunately you have not been allocated any ECMT permits currently.

Due to the very high numbers of applications we received across the UK and the limited number of permits available, we were unable to allocate permits to every applicant.

What happens next

If more permits become available, future application periods will be advertised (<?php echo $this->guidanceUrl; ?>).

You can check other types of permits available to UK hauliers (<?php echo $this->guidanceUrl; ?>).