Your ECMT permit issuing fee for application number <?php echo $this->applicationRef; ?> has now been received.

Your permits are now being processed and issued.

We will now post your paper permit and corresponding logbook by first class recorded delivery within the next 3 working days.

You can check ECMT guidance notes (<?php echo $this->guidanceUrl; ?>) on how to instruct your drivers, manage your paper permit and logbook and be fully compliant before going abroad.

View your application at <?php echo $this->permitsUrl; ?>.