Dear operator,
Important documentation relating to your Operator’s Licence <?php echo $this->escapeHtml($this->licNo); ?> has been sent by recorded delivery post to all known addresses. This is following the removal of your last TM, please ensure you respond within the stated deadline.
 PLEASE NOTE. A failure to respond to this letter will result in the traffic commissioner revoking the licence. The revocation of the licence would render unlawful the operation of vehicles for which an operator’s licence is required.
<?php if (!$this->registeredToSelfserve) : ?>

You can update your operator’s licence on-line, for example you can:
    • add or remove a transport manager
    • add more vehicles to your licence
    • increase the vehicle limit on your licence
    • change your licence type

To register for the on-line service, please use the following link:

https://www.vehicle-operator-licensing.service.gov.uk/auth/login/

The on-line service is straightforward and easy to use. It reduces the time required to progress most changes to licences. Changes to vehicles are effective immediately.

<?php endif; ?>
