Dear operator,

Important documentation relating to your Operator's Licence continuation for <?php echo $this->licNo . ' ' . $this->operatorName; ?> has been placed in your Self Service correspondence inbox.

Please note that you must print off the continuation document, sign it and return it to the office as soon as possible, highlighting any changes to the details on the document.

You will not be sent a paper copy of this document.

Sign in to your account at <?php echo $this->url; ?>.
