<div class="read-only">
    
    <?php
    
        if (isset($header) || isset($actions)) {
            echo $this->render('partials/read-only/header');
        }

        if (isset($multiItems)) {
            foreach ($multiItems as $items) {
                echo $this->render('partials/read-only/list', ['items' => $items]);
            }
        } elseif (isset($items)) {
            echo $this->render('partials/read-only/list', ['items' => $items]);
        }

        if (isset($freetext)) { 
        
    ?>
    
    <p><?php echo $freetext; ?></p>
    
    <?php }
    if (isset($markup)) {
        echo $markup;
    }
    if (isset($partial)) {
        echo $this->render('partials/' . $partial, $variables);
    }
    ?>

</div>
