Diolch am eich cais EBSR a dderbyniwyd ar <?php echo $this->submissionDate; ?> am y gwasanaeth bysiau lleol dilynol - <?php echo $this->registrationNumber; ?> - rhwng <?php echo $this->origin; ?> a <?php echo $this->destination; ?> gyda'r rhif gwasanaeth <?php echo $this->lineName; ?> i ddod i effaith ar <?php echo $this->startDate; ?>.

Gwrthodwyd eich cais. Felly ni allwch gychwyn, newid na chanslo'ch gwasanaeth fel y gwnaed cais amdano. Os gwnewch hynny, gallech wynebu camau disgyblu gan y Comisiynydd Traffig. Os oes gennych unrhyw amheuon, ffoniwch eich gweithiwr achos arferol neu e-bostiwch: operatorlicensing@otc.gsi.gov.uk

Rydym wedi copïo'r e-bost hwn i'r awdurdodau lleol dilynol: <?php echo $this->localAuthoritys; ?>.