Diolch am eich cyflwyniad Adnewyddu Data EBSR a dderbyniwyd ar <?php echo $this->submissionDate; ?> ar gyfer y gwasanaeth bysiau lleol dilynol - <?php echo $this->registrationNumber; ?> - rhwng <?php echo $this->origin; ?> a <?php echo $this->destination; ?> gyda'r rhif gwasanaeth <?php echo $this->lineName; ?> i ddod i effaith ar <?php echo $this->startDate; ?>.

Derbyniwyd eich cyflwyniad ac erbyn hyn diweddarwyd ein cofnodion llaw presennol gyda'r ffeil Cofrestru Electronig o Wasanaeth Bysiau (EBSR).

Rydym wedi copïo'r e-bost hwn i'r awdurdodau lleol dilynol: <?php echo $this->localAuthoritys; ?>.

Byddwch yn canfod copi o'r fersiwn PDF o'r manylion cofrestredig yn eich ardal ddogfennau. Gwiriwch y cynnwys a rhoi gwybod inni os oes unrhyw ddiffygion fel y gallwn eu cywiro cyn gynted â phosibl.