Diolch am eich cais EBSR a dderbyniwyd ar <?php echo $this->submissionDate; ?> am y gwasanaeth bysiau lleol dilynol  - <?php echo $this->registrationNumber; ?> - rhwng <?php echo $this->origin; ?> and <?php echo $this->destination; ?> gyda'r rhif gwasanaeth <?php echo $this->lineName; ?> i ddod i effaith ar <?php echo $this->startDate; ?>.

Derbyniwyd eich cais. Fodd bynnag rhaid ichi beidio â chychwyn na newid eich gwasanaeth tan y dyddiad y sonir amdano uchod. Os gwnewch hynny, gallech wynebu camau disgyblu gan y Comisiynydd Traffig.

Bydd hysbysiad o'r cais hwn yn ymddangos yn "Hysbysiadau ac Achosion" rhif cyhoeddiad <?php echo $this->publicationId; ?>. Rydym wedi copïo'r e-bost hwn i'r awdurdodau lleol dilynol: <?php echo $this->localAuthoritys; ?>.

Byddwch yn gweld copi o'r fersiwn PDF o'r manylion cofrestredig yn eich ardal ddogfennau. Gwiriwch y cynnwys a rhoi gwybod inni os oes unrhyw ddifffygion fel y gallwn eu datrys cyn gynted â phosibl.