CY - Vehicle Operator Licensing

CY - Your ECMT permit application <?php echo $this->escapeHtml($this->applicationRef); ?> has now been considered and processed.

CY - Application status: Unsuccessful

We need to inform you that you have not been successful with your permit application. This was mainly due to the limited number of permits in total available to us. We were also oversubscribed and received a very high number of applications from across the UK.

What happens next

We may run another allocation process in the near future. You might then be offered permits, if and when they become available to the UK Government to allocate.

You can consider applying for other types of international road haulage permits (<?php echo $this->guidanceUrl; ?>) that are also available to UK hauliers.

Please also bookmark our Guidance page (<?php echo $this->guidanceUrl; ?>) for future reference and the latest information.
