Your ECMT permit application <?php echo $this->applicationRef; ?> has now been received and will be processed.

As a result of your application and the allocation process you might be granted with:

* All of your permits required
* Some of your permits required
* None of your permits required

We will contact you when we have considered all applications that have been submitted to advise you if your application was successful, partially successful or unsuccessful.

By signing into your vehicle operator licence account you can:

* Check your application status
* Review your application
* Cancel your application

View your application at <?php echo $this->permitsUrl; ?>.
