Annwyl weithredwr,

Yn ddiweddar rydym wedi anfon e-bost atoch i'ch hysbysu bod gohebiaeth newydd ynghylch eich Trwydded Gweithredwr's <?php echo $this->licNo . ' ' . $this->operatorName; ?> wedi'i rhoi yn eich mewnflwch Gweithredwr Hunan Wasanaeth.

Rydym yn nodi nad yw hon wedi'i darllen eto. Mewngofnodwch i weld yr ohebiaeth cyn gynted â phosib.

Mewngofnodi i'ch cyfrif <?php echo $this->url; ?>.