Annwyl weithredwr,

Yn ddiweddar rydym wedi anfon e-bost atoch i'ch hysbysu bod dogfen ynghylch parhad eich Trwydded Gweithredwr'ar gyfer <?php echo $this->licNo . ' ' . $this->operatorName; ?> wedi'i rhoi yn eich mewnflwch Hunan Wasanaeth Gweithredwr.

Rydym yn nodi nad yw hon wedi'i darllen eto. Mewngofnodwch i weld yr ohebiaeth cyn gynted â phosibl.

Nodwch bod rhaid ichi brintio'r ddogfen barhad, ei llofnodi a'i dychwelyd i'r swyddfa cyn gynted â phosibl, gan amlygu unrhyw newidiadau i'r manylion ar y ddogfen.

Bydd methu â dychwelyd y ddogfen yn arwain at roi terfyn ar eich trwydded gweithredwr.

Mewngofnodi i'ch cyfrif <?php echo $this->url; ?>.
