Annwyl weithredwr,

Rhoddwyd dogfennaeth bwysig ynghylch parhad eich Trwydded Gweithredwr's am<?php echo $this->licNo . ' ' . $this->operatorName; ?> wedi'i rhoi yn eich mewnflwch gohebiaeth Hunan Wasanaeth.

Nodwch fod rhaid ichi brintio'r ddogfen barhad, ei llofnodi a'i dychwelyd i'r swyddfa cyn gynted â phosibl, gan amlygu unrhyw newidiadau i'r manylion ar y ddogfen.

Nid anfonir copi papur o'r ddogfen hon ichi.

Mewngofnodi i'ch cyfrif <?php echo $this->url; ?>.
