Annwyl weithredwr,

Rhoddwyd dogfennaeth bwysig yn ymwneud â pharhad eich Trwydded Gweithredwr <?php echo $this->licNo; ?> yn eich blwch derbyn gohebiaeth Hunanwasanaeth.

Y fersiwn Saesneg o’r ddogfen yw hon a byddwn yn trefnu i anfon fersiwn Gymraeg atoch cyn gynted â phosibl.

Sylwer bod yn rhaid i chi ei llofnodi a’i dychwelyd i’r swyddfa cyn gynted â phosibl, gan amlygu unrhyw newidiadau i unrhyw fanylion.

Mewngofnodwch i’ch cyfrif <?php echo $this->url; ?>
