Helô,

Mae <?php echo $this->organisation; ?> wedi'ch enwi fel Rheolwr Trafnidiaeth ar y cais am Drwydded Gweithredwr Cerbydau <?php echo $this->reference; ?>.

Cyn gallwn ystyried y cais, bydd angen ichi gyflwyno'ch manylion inni drwy ein gwasanaeth ar-lein.

Eich enw defnyddiwr yw: <?php echo $this->loginId; ?>

Byddwch yn derbyn ail e-bost gyda chyfrinair dros dro yn y ddwy awr nesaf. Os na fydd yn cyrraedd e-bostiwch notifications@vehicle-operator-licensing.service.gov.uk.

Mewngofnodi <?php echo $this->url; ?>.