<p>Thank you for your EBSR application received on <?php echo $this->escapeHtml($this->submissionDate); ?> for the
    following local bus service - <?php echo $this->escapeHtml($this->registrationNumber); ?> - between
    <?php echo $this->escapeHtml($this->origin); ?> and <?php echo $this->escapeHtml($this->destination); ?> with
    service number <?php echo $this->escapeHtml($this->lineName); ?> to come into effect on
    <?php echo $this->escapeHtml($this->startDate); ?>.</p>

<p>A new version of the <?php echo $this->escapeHtml($this->pdfType); ?> is now available for this registration. Please log
    on to view this if required.</p>

<p>Please do not reply directly to this e-mail by using the ‘reply’ function in your e-mail package as this is an
    automated facility that cannot handle incoming e-mails. If you need to contact us, please ring your usual
    caseworker or e-mail: <a href="mailto:notifications@vehicle-operator-licensing.service.gov.uk">notifications@vehicle-operator-licensing.service.gov.uk</a></p>