<p>Thank you for your EBSR application received on <?php echo $this->escapeHtml($this->submissionDate); ?> to withdraw
    the following local bus service.</p>

<p><?php echo $this->escapeHtml($this->registrationNumber); ?> - between
    <?php echo $this->escapeHtml($this->origin); ?> and <?php echo $this->escapeHtml($this->destination); ?> with
    service number <?php echo $this->escapeHtml($this->lineName); ?> is withdrawn.</p>