<?php /** @var Laminas\View\Renderer\PhpRenderer $this */ ?>
<p>Thank you for your EBSR application received on <?php echo $this->escapeHtml($this->submissionDate); ?> for the
following local bus service - <?php echo $this->escapeHtml($this->registrationNumber); ?> - between
<?php echo $this->escapeHtml($this->origin); ?> and <?php echo $this->escapeHtml($this->destination); ?> with
service number <?php echo $this->escapeHtml($this->lineName); ?> to come into effect on
<?php echo $this->escapeHtml($this->startDate); ?>.</p>

<p>Your application has been received and will be processed as soon as possible.
We have copied this e-mail to the following local authorities:
<?php echo $this->escapeHtml($this->localAuthoritys); ?>.</p>