<p>Your ECMT permit application <?php echo $this->escapeHtml($this->applicationRef); ?> has now been withdrawn as the issue fee has not been paid.</p>

<p>We advised in our previous email that you had 10 working days to accept the permits allocated after which they would be re-allocated. This period has now passed and the issue fee is not paid so the application is deemed to be withdrawn.</p>

<h3>What happens next</h3>

<p>Further permits may become available in the future but are not guaranteed.</p>

<p>You can consider applying for other types of <a href="https://www.gov.uk/guidance/international-authorisations-and-permits-for-road-haulage">international road haulage permits</a> that are also available to UK hauliers.</p>