<p>Hello,</p>

<p>You've been added to the Vehicle Operator Licensing service for 
<?php echo $this->escapeHtml($this->orgName); ?>.</p>

<p>Your username is: <strong><?php echo $this->escapeHtml($this->loginId); ?></strong></p>

<p>You’ll receive a second email with a temporary password in the next two hours. If it doesn’t arrive email <a href="mailto:notifications@vehicle-operator-licensing.service.gov.uk">notifications@vehicle-operator-licensing.service.gov.uk</a>.</p>

<p>
    <a href="<?php echo $this->escapeHtml($this->url); ?>">Sign in</a>
</p>