<p>Thank you for your EBSR application received on <?php echo $this->escapeHtml($this->submissionDate); ?> for the
    following local bus service - <?php echo $this->escapeHtml($this->registrationNumber); ?> - between
    <?php echo $this->escapeHtml($this->origin); ?> and <?php echo $this->escapeHtml($this->destination); ?> with
    service number <?php echo $this->escapeHtml($this->lineName); ?> came into effect on
    <?php echo $this->escapeHtml($this->startDate); ?>.</p>

<p>We would remind you that you must continue to operate the service until the cancellation date mentioned above.
    If you do not, you could face disciplinary action by the Traffic Commissioner.</p>

<p>Notice of this cancellation application will appear in "Notices and Proceedings" issue number
    <?php echo $this->escapeHtml($this->publicationId); ?>. We have copied this e-mail to the following local
    authorities: <?php echo $this->escapeHtml($this->localAuthoritys); ?>.</p>