<p>Thank you for your EBSR application received on <?php echo $this->escapeHtml($this->submissionDate); ?> for the
   following local bus service - <?php echo $this->escapeHtml($this->registrationNumber); ?> - between
   <?php echo $this->escapeHtml($this->origin); ?> and <?php echo $this->escapeHtml($this->destination); ?> with
    service number <?php echo $this->escapeHtml($this->lineName); ?>.</p>

<p>Your application for short notice under the Traffic Commissioners discretionary powers has been refused, therefore
   you must give the full notice period until you can start, change or cancel your service. If you do, you could face
   disciplinary action by the Traffic Commissioner.</p>

<p>The revised effective date will be <?php echo $this->escapeHtml($this->startDate); ?>.<br />
    If you are in any doubt, please ring your usual caseworker or e-mail:
    <a href="mailto:operatorlicensing@otc.gsi.gov.uk">operatorlicensing@otc.gsi.gov.uk</a><br />
    We have copied this e-mail to the following local authorities:
    <?php echo $this->escapeHtml($this->localAuthoritys); ?>.</p>