<p>Please find below a negative acknowledgement receipt from ERRU.</p>

<p>This requires identifying the correct recipient and forwarding to the
appropriate mailbox.</p>

<p>If GB, then identify the reason for negative acknowledgement, correct and
re-submit MSI via the INR web portal.</p>

<p>
Business case id: <?php echo $this->escapeHtml($this->notificationNumber); ?><br />
Sent at: <?php echo $this->escapeHtml($this->sentAt); ?><br />
From MS: <?php echo $this->escapeHtml($this->memberState); ?><br />
Originating authority: <?php echo $this->escapeHtml($this->originatingAuthority); ?><br />
Acknowledgement date/time: <?php echo $this->escapeHtml($this->notificationDateTime); ?><br />
</p>

<p>Error messages:
    <ul>
<?php foreach ($this->errorMessages as $message) { ?>
        <li><?php echo $this->escapeHtml($message); ?></li>
<?php } ?>
    </ul>
</p>

<p>(See attached file: <?php echo $this->escapeHtml($this->filename); ?>)</p>