<p>Hello,</p>

<p>
    The temporary password for your Vehicle Operator Licensing account is:
    <strong><?php echo $this->escapeHtml($this->password); ?></strong>
</p>

<p>
    <a href="<?php echo $this->escapeHtml($this->url); ?>">Sign in</a>
</p>

<p>
    <strong>Change your password</strong><br/>
    After you sign in you will need to change your password. You can do this in "Your account".
</p>