<p>Diolch am eich cais EBSR a dderbyniwyd ar  <?php echo $this->escapeHtml($this->submissionDate); ?> am y
    gwasanaeth bysiau dilynol - <?php echo $this->escapeHtml($this->registrationNumber); ?> - rhwng
    <?php echo $this->escapeHtml($this->origin); ?> a <?php echo $this->escapeHtml($this->destination); ?> gyda'r
    rhif gwasanaeth <?php echo $this->escapeHtml($this->lineName); ?> i ddod i effaith ar
    <?php echo $this->escapeHtml($this->startDate); ?>.</p>

<p>Derbyniwyd eich cais a chaiff ei brosesu cyn gynted â phosibl. Rydym wedi copïo'r e-bost hwn i'r
    awdurdodau lleol dilynol:
    <?php echo $this->escapeHtml($this->localAuthoritys); ?>.</p>