<p>CY - Your ECMT permit application <?php echo $this->escapeHtml($this->applicationRef); ?> has now been considered and processed.</p>

<h3>CY - Application status: Successful</h3>
<p>You have been allocated the full number of permits you applied for.
<ul>
    <li>Number of permits required: <?php echo $this->escapeHtml($this->permitsRequired); ?></li>
    <li>Number of permits granted: <?php echo $this->escapeHtml($this->permitsGranted); ?></li>
</ul>

<h3>Next steps</h3>
<p>You now need to pay the Permit Issuing total fee of £<?php echo $this->escapeHtml($this->issueFeeTotal); ?>
    (£<?php echo $this->escapeHtml($this->issueFeeAmount); ?> per permit) before receiving your paper based permit and
    corresponding logbook. These will be posted by first class recorded delivery.</p>

<p>You have <?php echo $this->escapeHtml($this->paymentDeadlineNumDays); ?> working days to pay for your allocated
    permits. If you do not pay the Permit Issuing fee by <?php echo $this->escapeHtml($this->issueFeeDeadlineDate); ?>
    the permits granted to your business will be automatically cancelled.</p>
<a href="<?php echo $this->awaitingFeeUrl; //replaced based on the env, so can't escape ?>">Pay for your permits</a>