<p>Your ECMT permit application <strong><?php echo $this->escapeHtml($this->applicationRef); ?></strong> has now been received and will be processed.</p>

<p>As a result of your application and the allocation process you might be granted with:</p>

<ul>
    <li>All of your permits required</li>
    <li>Some of your permits required</li>
    <li>None of your permits required</li>
</ul>

<p>Within the next 30 days you will receive an email informing if your application was successful, partially successful or unsuccessful.</p>

<p>By signing into your <a href="<?php echo $this->escapeUrl($this->url); ?>">vehicle operator licence account</a> you can:</p>

<ul>
    <li>Check your application status</li>
    <li>Review your application</li>
    <li>Cancel your application</li>
</ul>

<button href="<?php echo $this->escapeUrl($this->url); ?>">View your application</button>