<p>Your ECMT permit application <strong><?php echo $this->escapeHtml($this->applicationRef); ?></strong> has now been considered and processed.</p>

<h3 class="heading-small">Application status: Unsuccessful</h3>

<p>Unfortunately you have not been allocated any ECMT permits currently.</p>

<p>Due to the very high numbers of applications we received across the UK and the limited number of permits available,
    we were unable to allocate permits to every applicant.</p>

<h3 class="heading-small">What happens next</h3>

<p>If more permits become available, future application periods will be
    <a href="<?php echo $this->escapeHtml($this->guidanceUrl); ?>">advertised</a>.</p>

<p>You can <a href="<?php echo $this->escapeHtml($this->guidanceUrl); ?>">check</a> other types of permits available to
    UK hauliers.</p>
