<p>CY - Vehicle Operator Licensing</p>

<p>CY - Your ECMT permit application <strong><?php echo $this->escapeHtml($this->applicationRef); ?></strong> has now been considered and processed.</p>

<h3 class="heading-small">CY - Application status: Unsuccessful</h3>

<p>We need to inform you that you have not been successful with your permit application. This was mainly due to the limited number of permits in total available to us. We were also oversubscribed and received a very high number of applications from across the UK.</p>

<h3 class="heading-small">What happens next</h3>

<p>We may run another allocation process in the near future. You might then be offered permits, if and when they become available to the UK Government to allocate.</p>

<p>You can consider <a href="<?php echo $this->escapeHtml($this->guidanceUrl); ?>">applying for other types of international road haulage permits</a> that are also available to UK hauliers.</p>

<p>Please also bookmark our <a href="<?php echo $this->escapeHtml($this->guidanceUrl); ?>">Guidance page</a> for future reference and the latest information.</p>
