<p>Your ECMT permit issuing fee for application number <strong><?php echo $this->escapeHtml($this->applicationRef); ?></strong> has now been received.</p>

<p>Your permits are now being processed and issued.</p>

<p>We will now post your paper permit and corresponding logbook by first class recorded delivery within the next 3 working days.</p>

<p>You can check <a href="<?php echo $this->escapeHtml($this->guidanceUrl); ?>">ECMT guidance notes</a> on how to instruct your drivers, manage your paper permit and logbook and be fully compliant before going abroad.</p>

<a class="action--primary" href="<?php echo $this->permitsUrl; //replaced based on the env, so can't escape ?>">View issued permits</a>
