<h2>WELSH</h2>

<p>Hello,</p>
<p>
    <?php echo $this->organisation ?> has named you as a Transport Manager on Vehicle Operator Licence <?php echo $this->reference ?>.
</p>
<p>
    Before we can consider their application, you’ll need to submit your details to us.
</p>
<p>
    To do that <a href="<?php echo $this->signInLink ?>">sign in online</a> with your username (<?php echo $this->username ?>) and password.
</p>
<p>
    <b>Having problems?</b><br>
    <?php
    $url = ($this->isNi) ?
        'http://www.doeni.gov.uk/index/information/foi/recent-releases/publications-details.htm?docid=9994' :
        'https://www.gov.uk/government/publications/application-to-add-a-transport-manager-to-a-licence-tm1';
    ?>
    For advice see the <a href="<?php echo $url ?>">Transport Manager help guide</a> or
    <a href="mailto:operatorlicensing@otc.gsi.gov.uk">email us</a>.
</p>