<p>Helô,</p>

<p>
    Y cyfrinair dros dro ar gyfer eich cyfrif Trwyddedu Gweithredwyr Cerbydau yw:
    <strong><?php echo $this->escapeHtml($this->password); ?></strong>
</p>

<p>
    <a href="<?php echo $this->escapeHtml($this->url); ?>">Mewngofnodi</a>
</p>

<p>
    <strong>Newid eich cyfrinair</strong><br/>
    Wedi ichi fewngofnodi bydd angen ichi newid eich cyfrinair. Gallwch wneud hyn yn "Fy Nghyfrif".
</p>