<?php $title = 'Application for ' . $this->escapeHtml($data['permitType']); ?>
<!DOCTYPE html>
<html lang="en">

<head>

    <title><?php echo $title; ?></title>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <style>
        dl:after {
            content: "";
            display: table;
            clear: both;
        }

        h1 {
            font-size: 48px;
        }

        @media (max-width: 780px) {
            h1 {
                font-size: 36px;
            }
        }

        h2 {
            font-size: 36px;
        }

        @media (max-width: 780px) {
            h2 {
                font-size: 24px;
            }
        }

        h1 {
            line-height: 1.04167;
            max-width: 650px;
        }

        p {
            font-weight: 400;
            margin-bottom: .5em;
        }

        b,
        strong {
            font-weight: 700;
        }

        h1,
        h2,
        p,
        ul,
        ol {
            margin-top: 0;
        }

        h1:last-child,
        h2:last-child,
        p:last-child,
        ul:last-child,
        ol:last-child {
            margin-bottom: 0;
        }

        .text-area {
            width: 100%;
            max-width: 800px;
        }

        dt,
        dd {
            float: left;
            overflow: auto;
            margin: 0;
            padding: 0 2.5% 10px 0;
            width: 47.5%;
        }

        dd {
            font-weight: 600;
        }

        body {
            font-family: Arial, sans-serif;
            background: #fff;
            margin: 0 auto;
            max-width: 860px;
            padding: 0 20px;
            font-size: 16px;
            line-height: 1.4;
            padding-bottom: 50px;
        }

        h3 {
            margin: 0;
        }

        p:first-child {
            margin-top: 0;
        }

        p:last-child {
            margin-bottom: 0;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        ul.bullet {
            list-style: disc;
            margin: 10px;
            padding: 10px;
        }

        .list--bullet {
            margin-left: 20px;
            list-style: disc;
        }

        [type="text"] {
            display: block;
            padding: 10px;
            width: 100%;
        }

        @media print {
            .hide-print {
                display: none;
            }
        }

        .signature-box {
            margin: 30px 0;
            padding: 30px;
            background: #dee0e2;
            -webkit-print-color-adjust: exact;
        }

        .signature-box__column {
            width: 45%;
            margin: 0 5% 0 0;
        }

        .signature-box__label {
            font-weight: 600;
        }

        .signature-box__input {
            width: 100%;
            border: 2px solid #0b0c0c;
            margin-bottom: 20px;
        }

        .signature-box__input.signature {
            height: 100px;
        }

        .signature-box__input.date {
            width: 200px;
        }

        .signature-box__digital-signature .signature-box__label {
            width: 45%;
            display: inline-block;
            margin: 0 5% 20px 0;
        }

        .signature-box__digital-signature .signature-box__value {
            width: 45%;
            display: inline-block;
            margin-bottom: 20px;
        }

        .printable {
            padding-top: 60px;
        }

        @media print {
            .printable {
                padding-top: 20px;
            }
        }

        .printable__header {
            padding: 60px 0;
            clear: both;
        }

        @media print {
            .printable__header {
                padding: 40px 0;
            }
        }

        .printable__address {
            float: left;
        }

        .printable__section {
            clear: both;
        }
    </style>

</head>

<body>

    <div class="printable">

        <div class="printable__header">
            <h1><?php echo $title; ?></h1>
            <h2><?php echo $this->escapeHtml($data['operator']); ?> <?php echo $this->escapeHtml($data['ref']); ?></h2>
            <a class="hide-print" href="javascript:window.print()">Print this page</a>
        </div>

        <div class="printable__section">
            <dl>
                <dt>Licence selected</dt>
                <dd><?php echo $this->escapeHtml($data['licence']); ?></dd>
            </dl>
            <dl>
                <dt>I confirm that my ECMT permits will only be used by vehicles that are environmentally compliant with Euro 6 emissions standards.</dt>
                <dd><?php echo $this->escapeHtml($data['emissions']); ?></dd>
            </dl>
            <dl>
                <dt>I confirm that I will not undertake any cabotage journeys using an ECMT permit.</dt>
                <dd><?php echo $this->escapeHtml($data['cabotage']); ?></dd>
            </dl>
            <dl>
                <dt>In the next 12 months are you transporting goods to Austria, Greece, Hungary, Italy or Russia?</dt>
                <dd><?php echo $this->escapeHtml($data['limited-permits']); ?></dd>
            </dl>
            <dl>
                <dt>How many permits do you require for this licence?</dt>
                <dd><?php echo $this->escapeHtml($data['number-required']); ?></dd>
            </dl>
            <dl>
                <dt>How many international trips did you make in the last 12 months using this licence?</dt>
                <dd><?php echo $this->escapeHtml($data['trips']); ?></dd>
            </dl>
            <dl>
                <dt>In the last 12 months, what percentage of international trips did you make using this licence?</dt>
                <dd><?php echo $this->escapeHtml($data['int-journeys']); ?></dd>
            </dl>
            <dl>
                <dt>Select one sector you mainly transport goods in using this licence</dt>
                <dd><?php echo $this->escapeHtml($data['goods']); ?></dd>
            </dl>
        </div>

        <div class="printable__section">
            <ul class="bullet">
                <li>I have read the Guidance Notes (https://www.gov.uk/guidance/international-authorisations-and-permits-for-road-haulage) on how to use ECMT permits.</li>
                <li>I understand if a permit is issued it may exclude travel to Austria, Greece, Hungary, Italy and Russia as there are limited numbers of permits for travel to these countries.</li>
                <li>I understand that if a permit is issued I will be issued with a corresponding logbook which I must complete with full journey details before the start of a journey.</li>
                <li>I understand that I must carry a permit and corresponding logbook for the entire outbound and return journey.</li>
            </ul>
            <p><strong>I declare that the statements and information provided are true and that my application is correct. I understand that it is an offence to make a false declaration to obtain a permit.</strong></p>

        </div>

        <div class="signature-box">
            <div class="signature-box__column">
                <label for="" class="signature-box__label">Applicant's signature</label>
                <input type="text" class="signature-box__input signature" disabled="disabled">
                <label for="" class="signature-box__label">Full name in block capitals</label>
                <input type="text" class="signature-box__input name" disabled="disabled">
                <label for="" class="signature-box__label">Position in Company</label>
                <input type="text" class="signature-box__input position" disabled="disabled">
                <label for="" class="signature-box__label">Date</label>
                <input type="text" class="signature-box__input date" disabled="disabled">
            </div>
        </div>

        <div class="printable__address">
            <p><b>Return to:</b></p>
            <p>International Road Haulage Permit Office, Hillcrest House, 386 Harehills Lane, Leeds, LS9 6NF</p>
        </div>
    </div>

</body>
</html>
