<p>
    <b>By submitting this form you are confirming your status as an internal transport manager, an external transport manager or both.</b>
</p>

<p>I confirm that:</p>
<ul class="list--bullet">
    <li>I am resident in the European Community;</li>
    <li>I shall perform my tasks solely in the interests of the licence holder/applicant;</li>
    <li>I shall be the transport manager for a maximum of 4 operators, with a combined maximum total fleet of 50 vehicles; and</li>
    <li>I have a contract with the licence holder/applicant which specifies the tasks I must perform as transport manager. These include:
        <ul class="list--bullet">
            <li>The making of arrangements to ensure that drivers comply with drivers’ hours and tachograph rules and with speed limits;</li>
            <li>The making of arrangements to ensure that the vehicles are maintained properly, including the inspection of vehicles at the appropriate time and the action taken to remedy defects found;</li>
            <li>The reporting and recording of vehicle defects by drivers;</li>
            <li>The method of compilation and the accuracy of all records, which must be kept for a period of not less than 15 months;</li>
            <li>The making of arrangements to ensure that the vehicle/s are not overloaded;</li>
            <li>Ensuring that authorised vehicles will be kept at the authorised operating centre(s) when not in use;</li>
            <li>Where appropriate, notifying the relevant Traffic Commissioner (in writing) of all prosecutions and convictions concerning the operator, the drivers and me within 28 days of the court hearing;</li>
            <li>Notifying the relevant Traffic Commissioner of my resignation; and</li>
            <li>Any role that I have in:
                <ul class="list--bullet">
                    <li>Verifying contracts and documents;</li>
                    <li>Basic accounting;</li>
                    <li>Any other role in safety procedures.</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>

<p>
    <b>Should I fail to meet any of the above requirements I understand that the traffic commissioner has the power to disqualify me from being a transport manager in any European Union country. I also understand that I do not become a CPC holder for the licence(s) named until this is confirmed in writing by the Traffic Commissioner.</b>
</p>