<ul class="bullet">
    <li>You have read the <a href="https://www.gov.uk/guidance/international-authorisations-and-permits-for-road-haulage" target="_blank">Guidance Notes</a> on how to use international road haulage permits.</li>
    <li>You will comply fully with the conditions of use and terms and conditions under which the permits may be used.</li>
    <li>Your driver will carry the permit for the entire outbound and return journey and present it to any competent authority or inspectors.</li>
    <li>You understand that one permit is required for each vehicle you intend to use to transport goods to and from any EU or EEA country.</li>
</ul>
