<div class="signature-box">
    <div class="signature-box__column">
        <form>
            <label for="" class="signature-box__label">%s</label>
            <input type="text" class="signature-box__input signature" disabled="disabled">
            <label for="" class="signature-box__label">Full name in block capitals</label>
            <input type="text" class="signature-box__input name" disabled="disabled">
            <label for="" class="signature-box__label">Date</label>
            <input type="text" class="signature-box__input date" disabled="disabled">
        </form>
    </div>
</div>

<p>
    You must sign and return this form before we can consider your application.<br />
    <b>Return to: </b>%s
</p>
