<div class="signature-box">
    <div class="signature-box__digital-signature">
        <form>
            <div>
                <label class="signature-box__label">Operator's signature</label>
                <span class="signature-box__value">Signed by using GOV.UK Verify</span>
            </div>

            <div>
                <label class="signature-box__label">Signed by</label>
                <span class="signature-box__value">%s</span>
            </div>

            <div>
                <label class="signature-box__label">Date of Birth</label>
                <span class="signature-box__value">%s</span>
            </div>
            <div>
                <label class="signature-box__label">Signature date</label>
                <span class="signature-box__value">%s</span>
            </div>
        </form>
    </div>
</div>