<div class="signature-box">
    <div class="signature-box__digital-signature">
        <form>
            <div>
                <label class="signature-box__label">Transport Manager's signature</label>
                <span class="signature-box__value">Signed by using GOV.UK Verify</span>
            </div>

            <div>
                <label class="signature-box__label">Signed by</label>
                <span class="signature-box__value">%s</span>
            </div>

            <div>
                <label class="signature-box__label">Date of Birth</label>
                <span class="signature-box__value">%s</span>
            </div>
            <div>
                <label class="signature-box__label">Signature date</label>
                <span class="signature-box__value">%s</span>
            </div>
        </form>
    </div>
    <div class="signature-box__column">
        <form>
            <label class="signature-box__label">%s</label>
            <input type="text" class="signature-box__input signature">

            <label class="signature-box__label">Full name in block capitals</label>
            <input type="text" class="signature-box__input">

            <label class="signature-box__label">Date</label>
            <input type="text" class="signature-box__input date">
        </form>
    </div>
</div>

<p>You must sign and return this form before we can consider your application.</p>
<p><strong>Return to:</strong> %s</p>