<ul class="govuk-list govuk-list--bullet">
    <li>will comply fully with the conditions of use under which the permit may be used</li>
    <li>will carry the permit for the entire outbound and return journey and present it to any competent authority or inspectors</li>
</ul>
<p class="govuk-body">You also confirm that you understand that a permit is required for all countries you are travelling to and transiting through.</p>
