<p>
    I declare that the statements of fact or expectation provided in support of this application are correct.
</p>
<p>
    I understand that it is the responsibility of the applicant to ensure that they have the required experience and
    training prior to making an application for an operator's licence. I confirm that by signing this application that I
    understand the responsibilities and requirements of holding a goods vehicle operator's licence and will ensure that
    I will keep updated on those requirements.
</p>
<p>
    I understand that I must notify the traffic commissioner of any relevant conviction of the applicant incurred since
    making the application and that a failure to do so is an offence.
</p>
<p>
    I understand that any changes which occur during the consideration of an application, information which materially
    changes from that originally declared when the application was first submitted, must be notified to the traffic
    commissioner.
</p>
<p>
    I understand that if a licence is issued it will authorise a maximum number of vehicles and trailers that may be
    used under it at any one time, and that it is an offence to use more vehicles or trailers than permitted under the
    terms of the licence.
</p>
<p>
    I understand that by signing this application I am accepting that the following undertakings will be recorded on the
    licence:
</p>



<ul class="list--bullet">
    <li>The laws relating to the driving and operation of vehicles will be observed;</li>
    <li>The rules on drivers hours and tachographs are observed and proper records are kept for at least 12 months, and
        that these are made available on request;
    </li>
    <li>Vehicles and trailers are not overloaded or operated with an insecure load;</li>
    <li>Vehicles will operate within speed limits;</li>
    <li>Vehicles and trailers, including hired vehicles and trailers, are kept in a fit and serviceable condition;</li>
    <li>Drivers report promptly any defects or symptoms of defects that could prevent the safe operation of vehicles
        and/or trailers, and that any defects are recorded in writing;
    </li>
    <li>Records are kept (for 15 months) of all driver defect reports, all safety inspections, routine maintenance and
        repairs to vehicles and trailers repair reports, and these are made available on request;
    </li>
</ul>

<p>
    I understand that if a licence is issued it will be subject to the following conditions:
</p>
<p>
    a) That the licence holder, shall, within 28 days of their occurrence, inform the traffic commissioner of any:
</p>

<ul class="list--bullet">
    <li>Changes in the maintenance and safety inspection arrangements;</li>
    <li>Changes in the ability to ensure authorised vehicles are being operated safely and not causing danger to the
        public;
    </li>
    <li>Changes in the ownership of the business including partnership arrangements. Company changes in shareholding
        need not be notified unless they cause a change in the control of the Company;
    </li>
    <li>Events which affect:
        <ol type="i" class="validation-summary__list">
            <li>The fitness of the licence holder, in particular, relevant convictions as defined in schedule 3 to the
                1995 Act (this includes the issue of a fixed penalty notice or conditional offer under Part 3 of the
                Road Traffic Offenders Act 1988);
            </li>
            <li>The requirement for the licence holder to have the appropriate financial resources (including details of
                any bankruptcy, liquidation, sequestration of estate or entry into administration of the holder of the
                appointment of a receiver, manager or trustee);
            </li>
        </ol>
    </li>
</ul>
<p>b) In respect of each operating centre specified, that the number of authorised motor vehicles and the number of
    authorised trailers kept there will not exceed the maximum numbers recorded against the operating centre on this
    licence.
</p>

<p>Any failure to comply with the statements made to obtain a licence, conditions or undertakings recorded on the
    licence may result in the licence being revoked, suspended or curtailed; and that failure to comply with the
    conditions is a criminal offence.
</p>
%s
