<form>
    <div class="field ">
        <label>Your full name in block capitals</label>
        <input type="text" class="medium" >
    </div>
    <div class="field inline-70">
        <label>Signed</label>
        <input type="text" class="medium" >
    </div>
    <div class="field inline-30">
        <label>Dated</label>
        <input type="text" class="medium" >
    </div>
    <div class="field ">
        <label>Position in business - please tick <strong>one</strong> below</label>
        <label class="inline"><input type="checkbox" >Owner</label>
        <label class="inline"><input type="checkbox" >Partner</label>
        <label class="inline"><input type="checkbox" >Director</label>
    </div>

    <div class="field ">
        <label>Delegated officer of any other organisation</label>
        <input type="checkbox" >
    </div>
</form>