<!DOCTYPE html>
<html lang="en">

    <head>

        <title>GOV.UK</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <style>

            html, body, 
            button, input, 
            table, td, th {
                font-family: Arial, sans-serif;
            }

            .main {
                max-width: 600px;
            }

            .header {
                background: black;
                padding: 10px;
                font-weight: bold;
            }

            .logo img,
            .crown {
                display: inline-block;
                vertical-align: middle;
            }

            .logo img {
                width: 35px;
                height: 31px;
                margin-top: -1px;
                margin-right: 5px;
            }

            .crown {
                font-size: 30px;
                color: white;
                text-decoration: none;
            }

        </style>

    </head>

    <body class="email-template">

        <div class="header" style="background: black; padding: 10px; font-weight: bold;">

            <div class="logo">
                <font face="arial, sans-serif">
                    <img 
                         width="35" 
                         height="31" 
                         src="https://www.carersallowance.service.gov.uk/assets/images/crown.png" 
                         style="display: inline-block; 
                                vertical-align: middle; 
                                margin-right: 5px;" />
                  
                    <div 
                         class="crown" 
                         style="display: inline-block; 
                                vertical-align: middle; 
                                font-size: 30px; 
                                color: white; 
                                text-decoration: none;">
                        GOV&#8203;.&#8203;UK
                    </div>
                </font>
            </div>

        </div>

        <div class="main" style="max-width: 600px">

            <font face="arial, sans-serif">

                <br />

                <h1 class="form-title heading-large">Vehicle Operator Licensing</h1>

                <?php echo $this->content ?>

            </font>

        </div><!-- main -->

        <br />

        <div class="footer">
            <p><b>Sent by Vehicle Operator Licensing</b></p>
            <!--
            <p style="font-size: 10px; color: #BFC1C3;">Copyright/reference</p>
            -->
        </div>

    </body>

</html>
