<p>Diolch am eich cais EBSR a dderbyniwyd ar <?php echo $this->escapeHtml($this->submissionDate); ?> am y
    gwasanaeth bysiau lleol dilynol - <?php echo $this->escapeHtml($this->registrationNumber); ?> - rhwng
    <?php echo $this->escapeHtml($this->origin); ?> a <?php echo $this->escapeHtml($this->destination); ?> gyda'r rhif
    gwasanaeth <?php echo $this->escapeHtml($this->lineName); ?> i ddod i effaith ar
    <?php echo $this->escapeHtml($this->startDate); ?>.</p>

<p>Gwrthodwyd eich cais. Felly ni allwch gychwyn, newid na chanslo'ch gwasanaeth fel y gwnaed cais amdano.
    Os gwnewch hynny, gallech wynebu camau disgyblu gan y Comisiynydd Traffig.
    Os gwnaethoch gais am gais rhybudd byr efallai byddwch am ddiwygio'r dyddiad cychwyn a'i ail-gyflwyno.
    Os oes gennych unrhyw amheuon, ffoniwch eich gweithiwr achos arferol neu
    e-bostiwch: <a href="mailto:operatorlicensing@otc.gsi.gov.uk">operatorlicensing@otc.gsi.gov.uk</a></p>

<p>Rydym wedi copïo'r e-bost hwn i'r awdurdodau lleol dilynol:
    <?php echo $this->escapeHtml($this->localAuthoritys); ?>.</p>