<p>Diolch am eich cyflwyniad Adnewyddu Data EBSR a dderbyniwyd ar <?php echo $this->escapeHtml($this->submissionDate); ?>
    ar gyfer y gwasanaeth bysiau lleol dilynol - <?php echo $this->escapeHtml($this->registrationNumber); ?> - rhwng
    <?php echo $this->escapeHtml($this->origin); ?> a <?php echo $this->escapeHtml($this->destination); ?> gyda'r rhif
    gwasanaeth <?php echo $this->escapeHtml($this->lineName); ?> i ddod i effaith ar
    <?php echo $this->escapeHtml($this->startDate); ?>.</p>

<p>Derbyniwyd eich cyflwyniad ac erbyn hyn diweddarwyd ein cofnodion llaw presennol gyda'r ffeil Cofrestru 
    Electronig o Wasanaeth Bysiau (EBSR).</p>
<p>Rydym wedi copïo'r e-bost hwn i'r awdurdodau lleol dilynol: <?php echo $this->escapeHtml($this->localAuthoritys); ?>.</p>
<p>Byddwch yn canfod copi o'r fersiwn PDF o'r manylion cofrestredig yn eich ardal ddogfennau. 
    Gwiriwch y cynnwys a rhoi gwybod inni os oes unrhyw ddiffygion fel y gallwn eu cywiro cyn gynted â phosibl.</p>