<p>Annwyl weithredwr,</p>

<p>Yn ddiweddar rydym wedi anfon e-bost atoch i'ch hysbysu bod dogfen ynghylch parhad eich Trwydded
    Gweithredwr&rsquo;ar gyfer <?php echo $this->escapeHtml($this->licNo) . ' ' . $this->escapeHtml($this->operatorName); ?>
    wedi'i rhoi yn eich mewnflwch Hunan Wasanaeth Gweithredwr.</p>

<p>Rydym yn nodi nad yw hon wedi'i darllen eto. Mewngofnodwch i weld yr ohebiaeth cyn gynted â phosibl.</p>

<p>Nodwch bod rhaid ichi brintio'r ddogfen barhad, ei llofnodi a'i dychwelyd i'r swyddfa cyn gynted â phosibl, gan
    amlygu unrhyw newidiadau i'r manylion ar y ddogfen.</p>

<p><b>Bydd methu â dychwelyd y ddogfen yn arwain at roi terfyn ar eich trwydded gweithredwr.</b></p>

<p>
    <a href="<?php echo $this->escapeHtml($this->url); ?>">Mewngofnodi i'ch cyfrif</a>
</p>
