<p>Annwyl weithredwr,</p>

<p>Yn ddiweddar rydym wedi anfon e-bost atoch i'ch hysbysu bod gohebiaeth newydd ynghylch eich Trwydded
    Gweithredwr&rsquo;s <?php echo $this->escapeHtml($this->licNo) . ' ' . $this->escapeHtml($this->operatorName); ?> wedi'i rhoi yn eich mewnflwch Gweithredwr
    Hunan Wasanaeth.</p>

<p>Rydym yn nodi nad yw hon wedi'i darllen eto. Mewngofnodwch i weld yr ohebiaeth cyn gynted â phosib.</p>

<p>
    <a href="<?php echo $this->escapeHtml($this->url); ?>">Mewngofnodi i'ch cyfrif</a>
</p>
