<p>Annwyl weithredwr,</p>

<p>Rhoddwyd dogfennaeth bwysig yn ymwneud â’ch Trwydded Gweithredwr <?php echo $this->escapeHtml($this->licNo); ?>
yn eich blwch derbyn gohebiaeth Hunanwasanaeth.</p>

<p>Y fersiwn Saesneg o’r ddogfen yw hon a byddwn yn trefnu i anfon fersiwn Gymraeg atoch cyn gynted â phosibl.</p>

<p>
    <a href="<?php echo $this->escapeHtml($this->url); ?>">Mewngofnodwch i’ch cyfrif</a>
</p>
