<p>Helô,</p>

<p>Mae <?php echo $this->escapeHtml($this->organisation); ?> wedi'ch enwi fel Rheolwr Trafnidiaeth ar y cais am
    Drwydded Gweithredwr Cerbydau <?php echo $this->escapeHtml($this->reference); ?>.</p>

<p>Cyn gallwn ystyried y cais, bydd angen ichi gyflwyno'ch manylion inni drwy ein gwasanaeth ar-lein.</p>

<p>Eich enw defnyddiwr yw: <strong><?php echo $this->escapeHtml($this->loginId); ?></strong></p>

<p>Byddwch yn derbyn ail e-bost gyda chyfrinair dros dro yn y ddwy awr nesaf. Os na fydd yn cyrraedd
    e-bostiwch <a href="mailto:notifications@vehicle-operator-licensing.service.gov.uk">notifications@vehicle-operator-licensing.service.gov.uk</a>.</p>

<p>
    <a href="<?php echo $this->escapeHtml($this->url); ?>">Mewngofnodi</a>
</p>