<p><b>Translated to Welsh</b></p>
<p>Hello,</p>

<p>You've been added to the Vehicle Operator Licensing service for <?php echo $this->orgName ?>.</p>

<p>Your username is: <strong><?php echo $this->loginId ?></strong></p>

<p>You’ll receive a second email with a temporary password in the next two hours. If it doesn’t arrive email <a href="mailto:operatorlicensing@otc.gsi.gov.uk">operatorlicensing@otc.gsi.gov.uk</a>.</p>

<p>
    <a href="<?php echo $this->url; ?>">Sign in</a>
</p>