<p>Helô,</p>

<p>Mae un o ddefnyddwyr eich cyfrif Trwyddedu Gweithredwyr Cerbydau wedi anghofio eu henw defnyddiwr.</p>

<p>Fel y gweinyddydd, bydd angen ichi roi'r wybodaeth hon iddynt eich hunan. Gallwch ei chanfod yn ardal rheoli 
    defnyddwyr eich cyfrif.</p>

<p>Eich enw defnyddiwr yw: <strong><?php echo $this->escapeHtml($this->loginId); ?></strong></p>

<p>
    <a href="<?php echo $this->escapeHtml($this->url); ?>">Mewngofnodi</a>
</p>