<p>
    Mae Adran 12(1)(b) o Ddeddf Trafnidiaeth 1985 (fel y’i diwygiwyd) yn mynnu bod pob ymgeisydd am drwyddedau
    gweithredwyr cerbydau gwasanaeth cyhoeddus cyfyngedig arbennig yn datgan yn eu cais eu bod yn bwriadu cynnig
    gwasanaeth bws lleol cofrestredig. Rydych felly’n gwneud y datganiad canlynol wrth gyflwyno’r cais hwn
</p>
<p>
    Rwy’n cadarnhau fy mod yn bwriadu defnyddio un neu fwy o dacsis trwyddedig neu gerbydau hurio preifat i ddarparu
    gwasanaeth lleol.
    Rwy’n ymgeisio am drwydded gweithredwr cerbydau gwasanaeth cyhoeddus cyfyngedig arbennig. Rwy’n datgan fy mod:
</p>
<ul class="list--bullet">
    <li>
        Y datganiadau a wnaed yn y cais hwn yn gywir. Deallaf ei bod yn drosedd gwneud datganiad anghywir;
    </li>
    <li>Yr ymgeisydd yw deilydd y drwydedd(au) tacsi neu gerbyd hurio preifat a restrir yn y cais hwn;</li>
    <li>
        Bydd pob cerbyd a ddefnyddir dan drwydded cyfyngedig arbennig gweithredwr PSV yn un lle bydd gan yr ymgeisydd
        drwydded tacsi neu gerbyd hurio preifat ar eu cyfer;
    </li>
    <li>
        Ni chaniatieir i unrhyw gerbyd a ddefnyddir dan drwydded cyfyngedig arbennig gweithredwr PSV yn un lle bydd gan
        yr ymgeisydd gael ei ddefnyddio ar gyfer unrhyw bwrpas ar wahân i ddarparu gwasanaeth lleol gydag un neu ragor o
        fannau stopio o fewn yr ardal y cymeradwywyd y drwydded berthnasol ar ei chyfer ar gyfer y cerbyd hwnnw.
    </li>
</ul>