<ul class="bullet">
    <li>rydych wedi darllen y <a href="https://www.gov.uk/guidance/international-road-haulage-removal-permits" target="_blank">nodiadau cyfarwyddyd</a> ar sut i ddefnyddio trwyddedau symud rhyngwladol ECMT.</li>
    <li>byddwch yn cydymffurfio'n llawn â'r amodau defnyddio ar gyfer defnyddio'r trwyddedau.</li>
    <li>rydych yn deall bod yn rhaid i chi gael Tystysgrif Cydymffurfio a Thystysgrif Diogelwch ar y Ffyrdd ar gyfer pob cerbyd a threlar rydych yn bwriadu ei ddefnyddio.</li>
    <li>bydd eich gyrrwr yn cario'r drwydded a'r tystysgrifau ar gyfer y daith gyfan a'r daith yn ôl ac yn ei chyflwyno i unrhyw awdurdod neu arolygwyr cymwys.</li>
    <li>mae eich cwmni'n defnyddio offer a staff arbenigol i ymgymryd â gweithrediadau symud.</li>
    <li>rydych yn deall mai dim ond ar gyfer symud yn rhyngwladol rhwng aelod-wledydd ECMT y gellir defnyddio'r drwydded hon.</li>
    <li>yr ydych yn deall, wrth gludo, mai dim ond i ddarparu nwyddau symud ac eiddo busnes i wledydd eraill ECMT y gallwch ei ddefnyddio.</li>
</ul>
