<ul class="bullet">
    <li>Rydych wedi darllen y <a href="https://www.gov.uk/guidance/international-authorisations-and-permits-for-road-haulage" target="_blank">Nodiadau Cyfarwyddyd</a> ar sut i ddefnyddio hawlenni cludo nwyddau rhyngwladol.</li>
    <li>Byddwch yn cydymffurfio'n llawn â'r amodau defnyddio a'r telerau a'r amodau y gellir defnyddio'r hawlenni oddi danynt.</li>
    <li>Bydd eich gyrrwr yn cario'r hawlen ar gyfer y daith gyfan allan a'r daith yn ôl a'i chyflwyno i unrhyw awdurdod cymwys neu arolygwyr.</li>
    <li>Rydych yn deall bod angen un hawlen ar gyfer pob cerbyd rydych yn bwriadu ei ddefnyddio i gludo nwyddau i ac o unrhyw wlad yn yr UE neu'r AEE.</li>
</ul>
