<li>
    rhaid i mi fedru profi fod gennyf drefniant ffurfiol i gael mynediad bob amser at o leiaf un cerbyd sydd wedi ei
    gofrestru neu sy’n gweithredu yng Ngogledd Iwerddon. Gallai hyn fod drwy ddynodi cerbyd penodol i’w ddefnyddio dan
    Drwydded-O neu drwy ddangos ar gais fod gennyf i (deiliad y drwydded) gerbyd ar gael – felly gall cerbydau fod naill
    ai yn eiddo yn llwyr neu gael eu dal trwy hur-bwrcasu, trefniant llogi/prydlesu neu fath arall o drefniant ffurfiol;
</li>
<li>
    mae gennyf sefydliad yng Ngogledd Iwerddon sydd ag adeilad lle cadwaf ddogfennau busnes craidd. Mae’r rhain yn
    cynnwys (o leiaf) dogfennau cyfrifyddu a rheoli personél a data ar amser gyrru a gorffwys. Rwy’n deall nad yw’r
    defnydd o Flwch PO neu gyfeiriad trydydd parti yn dderbyniol.
</li>