Diolch am eich cais EBSR a ddaeth i law ar <?php echo $this->submissionDate; ?> ar gyfer y gwasanaeth bws lleol a ganlyn - <?php echo $this->registrationNumber; ?> - rhwng <?php echo $this->origin; ?> a <?php echo $this->destination; ?> â rhif gwasanaeth <?php echo $this->lineName; ?>.

Mae eich cais am rybudd byr dan rymoedd diamod y Comisiynwyr Traffig wedi ei wrthod, felly mae’n rhaid i chi roi’r cyfnod rhybudd llawn cyn y medrwch ddechrau, newid neu ddileu eich gwasanaeth. Os na fyddwch yn gwneud hyn, fe allwch wynebu achos o ddisgyblaeth gan y Comisiynydd Traffig.

Y dyddiad effeithiol diwygiedig fydd <?php echo $this->startDate; ?>.
Os oes gennych unrhyw amheuon, rhowch ganiad i’ch gweithiwr achos arferol neu e-bostiwch: operatorlicensing@otc.gsi.gov.uk
Rydym wedi copïo’r e-bost hwn i’r awdurdodau lleol a ganlyn:
<?php echo $this->localAuthoritys; ?>.
