Diolch am eich cais EBSR a dderbyniwyd ar <?php echo $this->submissionDate; ?> am y gwasanaeth bysiau lleol dilynol - <?php echo $this->registrationNumber; ?> - rhwng <?php echo $this->origin; ?> a <?php echo $this->destination; ?> gyda'r rhif gwasanaeth <?php echo $this->lineName; ?> a ddaeth i effaith ar <?php echo $this->startDate; ?>.

Hoffem eich atgoffa bod rhaid ichi barhau i weithredu'r gwasanaeth tan y dyddiad canslo y sonir amdano uchod. Os na wnewch, gallech wynebu camau disgyblu gan y Comisiynydd Traffig.

Ymddengys hysbysiad o'r cais hwn i ganslo yn "Hysbysiadau ac Achosion" rhif cyhoeddiad <?php echo $this->publicationId; ?>. Rydym wedi copïo'r e-bost hwn i'r awdurdodau lleol dilynol: <?php echo $this->localAuthoritys; ?>.