<?php if ($this->hasBusData) { ?>
Diolch am eich cais EBSR a dderbyniwyd ar <?php echo $this->submissionDate; ?>am y gwasanaeth bysiau lleol dilynol - <?php echo $this->registrationNumber; ?> - rhwng <?php echo $this->origin; ?> a <?php echo $this->destination; ?> gyda'r rhif gwasanaeth <?php echo $this->lineName; ?> i ddod i effaith ar <?php echo $this->startDate; ?>.
<?php } else { ?>
Diolch am eich cais EBSR a dderbyniwyd ar <?php echo $this->submissionDate; ?>.
<?php } ?>

Yn anffodus mae'ch cais wedi methu ein gwiriadau cychwynnol ar uniondeb y data. Felly NID ydym weddi'i gopïo i'r awdurdodau lleol a restrir yn eich XML TransXChange file.

Rydym wedi ceisio canfod y problemau a rhoi cliwiau ichi ynghylch ble i ganfod y gwallau. Fodd bynnag nid yw'n bosibl ini restru pob gwall ac ateb bosibl, felly rydym yn argymell eich bod yn edrych ar eich ffeil ddata eto er mwyn sicrhau ei bod yn cydymffurfio â'r amlinelliad data cofrestru perthnasol. Rydym yn awgrymu eich bod yn cychwyn trwy edrych ar y gwallau dilynol:
