We have already notified you that your ECMT permit application <?php echo $this->applicationRef; ?>  was unsuccessful in the first round of allocation.

The EU is close to agreeing a new law meaning UK operators will be able to carry out road haulage to EU member states until 31 December 2019. The new rules are set to be approved by the EU Parliament and Council in March and once agreed will allow you to make most journeys without a permit:

* You will be able to travel to any EU Member State (empty or laden) and return (empty or laden).
* You will be allowed to undertake a limited amount of 'cross-trade' and 'cabotage' work on a transitional basis – two such journeys per week for four months, reducing to one journey per week for the next three months.
* The proposed EU law will however not allow permit-free access to non-EU countries. You will require an ECMT permit to transit EU Member States to a 3rd countries such as Switzerland or Turkey.

We expect that ECMT permits will only be needed for:

* Operators wishing to undertake more than one cross-trade load as part of their journey. ECMT permits authorise up to 3 cross-trade loads.
* Operators who travel to non-EU Member States, through EU Member States – so for instance to Switzerland or Ukraine.

ECMT permits do not allow cabotage.

What happens next

We will write again urgently to let you know as soon as the new rules are finalised.

In addition, we have secured additional ECMT permits. Your application will automatically be considered for these permits and we will notify you if you receive any of these permits.

To find out the latest information plus details about any future application periods, please bookmark our Guidance page (<?php echo $this->guidanceUrl; ?>) for your reference.