<?php

namespace DoctrineORMModule\Proxy\__CG__\Olcs\Db\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Organisation extends \Olcs\Db\Entity\Organisation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'leadTcArea', 'sicCode', 'type', 'companyOrLlpNo', 'name', 'isMlh', 'companyCertSeen', 'irfoNationality', 'allowEmail', 'id', 'lastModifiedBy', 'createdBy', 'viAction', 'isIrfo', 'lastModifiedOn', 'createdOn', 'version');
        }

        return array('__isInitialized__', 'leadTcArea', 'sicCode', 'type', 'companyOrLlpNo', 'name', 'isMlh', 'companyCertSeen', 'irfoNationality', 'allowEmail', 'id', 'lastModifiedBy', 'createdBy', 'viAction', 'isIrfo', 'lastModifiedOn', 'createdOn', 'version');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Organisation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentifier', array());

        return parent::getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeadTcArea($leadTcArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeadTcArea', array($leadTcArea));

        return parent::setLeadTcArea($leadTcArea);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeadTcArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeadTcArea', array());

        return parent::getLeadTcArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setSicCode($sicCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSicCode', array($sicCode));

        return parent::setSicCode($sicCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getSicCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSicCode', array());

        return parent::getSicCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyOrLlpNo($companyOrLlpNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyOrLlpNo', array($companyOrLlpNo));

        return parent::setCompanyOrLlpNo($companyOrLlpNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyOrLlpNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyOrLlpNo', array());

        return parent::getCompanyOrLlpNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsMlh($isMlh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsMlh', array($isMlh));

        return parent::setIsMlh($isMlh);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsMlh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsMlh', array());

        return parent::getIsMlh();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyCertSeen($companyCertSeen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyCertSeen', array($companyCertSeen));

        return parent::setCompanyCertSeen($companyCertSeen);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyCertSeen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyCertSeen', array());

        return parent::getCompanyCertSeen();
    }

    /**
     * {@inheritDoc}
     */
    public function setIrfoNationality($irfoNationality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIrfoNationality', array($irfoNationality));

        return parent::setIrfoNationality($irfoNationality);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrfoNationality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrfoNationality', array());

        return parent::getIrfoNationality();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowEmail($allowEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowEmail', array($allowEmail));

        return parent::setAllowEmail($allowEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllowEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllowEmail', array());

        return parent::getAllowEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function clearProperties($properties = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearProperties', array($properties));

        return parent::clearProperties($properties);
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastModifiedBy($lastModifiedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastModifiedBy', array($lastModifiedBy));

        return parent::setLastModifiedBy($lastModifiedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastModifiedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastModifiedBy', array());

        return parent::getLastModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setViAction($viAction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViAction', array($viAction));

        return parent::setViAction($viAction);
    }

    /**
     * {@inheritDoc}
     */
    public function getViAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViAction', array());

        return parent::getViAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsIrfo($isIrfo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsIrfo', array($isIrfo));

        return parent::setIsIrfo($isIrfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsIrfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsIrfo', array());

        return parent::getIsIrfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastModifiedOn($lastModifiedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastModifiedOn', array($lastModifiedOn));

        return parent::setLastModifiedOn($lastModifiedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastModifiedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastModifiedOn', array());

        return parent::getLastModifiedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastModifiedOnBeforeUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastModifiedOnBeforeUpdate', array());

        return parent::setLastModifiedOnBeforeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn($createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', array($createdOn));

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', array());

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOnBeforePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOnBeforePersist', array());

        return parent::setCreatedOnBeforePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', array($version));

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', array());

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersionBeforePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersionBeforePersist', array());

        return parent::setVersionBeforePersist();
    }

}
