<?php

namespace DoctrineORMModule\Proxy\__CG__\Olcs\Db\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Licence extends \Olcs\Db\Entity\Licence implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'tachographIns', 'enforcementArea', 'trailersInPossession', 'fabsReference', 'grantedDate', 'reviewDate', 'feeDate', 'surrenderedDate', 'safetyInsTrailers', 'safetyInsVehicles', 'safetyIns', 'safetyInsVaries', 'niFlag', 'tachographInsName', 'psvDiscsToBePrintedNo', 'translateToWelsh', 'id', 'licenceType', 'status', 'goodsOrPsv', 'lastModifiedBy', 'trafficArea', 'organisation', 'createdBy', 'licNo', 'viAction', 'totAuthTrailers', 'totAuthVehicles', 'totAuthSmallVehicles', 'totAuthMediumVehicles', 'totAuthLargeVehicles', 'totCommunityLicences', 'expiryDate', 'inForceDate', 'createdOn', 'lastModifiedOn', 'version');
        }

        return array('__isInitialized__', 'tachographIns', 'enforcementArea', 'trailersInPossession', 'fabsReference', 'grantedDate', 'reviewDate', 'feeDate', 'surrenderedDate', 'safetyInsTrailers', 'safetyInsVehicles', 'safetyIns', 'safetyInsVaries', 'niFlag', 'tachographInsName', 'psvDiscsToBePrintedNo', 'translateToWelsh', 'id', 'licenceType', 'status', 'goodsOrPsv', 'lastModifiedBy', 'trafficArea', 'organisation', 'createdBy', 'licNo', 'viAction', 'totAuthTrailers', 'totAuthVehicles', 'totAuthSmallVehicles', 'totAuthMediumVehicles', 'totAuthLargeVehicles', 'totCommunityLicences', 'expiryDate', 'inForceDate', 'createdOn', 'lastModifiedOn', 'version');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Licence $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentifier', array());

        return parent::getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function setTachographIns($tachographIns)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTachographIns', array($tachographIns));

        return parent::setTachographIns($tachographIns);
    }

    /**
     * {@inheritDoc}
     */
    public function getTachographIns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTachographIns', array());

        return parent::getTachographIns();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnforcementArea($enforcementArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnforcementArea', array($enforcementArea));

        return parent::setEnforcementArea($enforcementArea);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnforcementArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnforcementArea', array());

        return parent::getEnforcementArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrailersInPossession($trailersInPossession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrailersInPossession', array($trailersInPossession));

        return parent::setTrailersInPossession($trailersInPossession);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrailersInPossession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrailersInPossession', array());

        return parent::getTrailersInPossession();
    }

    /**
     * {@inheritDoc}
     */
    public function setFabsReference($fabsReference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFabsReference', array($fabsReference));

        return parent::setFabsReference($fabsReference);
    }

    /**
     * {@inheritDoc}
     */
    public function getFabsReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFabsReference', array());

        return parent::getFabsReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrantedDate($grantedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrantedDate', array($grantedDate));

        return parent::setGrantedDate($grantedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrantedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrantedDate', array());

        return parent::getGrantedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setReviewDate($reviewDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReviewDate', array($reviewDate));

        return parent::setReviewDate($reviewDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getReviewDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviewDate', array());

        return parent::getReviewDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeeDate($feeDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeeDate', array($feeDate));

        return parent::setFeeDate($feeDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeeDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeeDate', array());

        return parent::getFeeDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurrenderedDate($surrenderedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurrenderedDate', array($surrenderedDate));

        return parent::setSurrenderedDate($surrenderedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurrenderedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurrenderedDate', array());

        return parent::getSurrenderedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSafetyInsTrailers($safetyInsTrailers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSafetyInsTrailers', array($safetyInsTrailers));

        return parent::setSafetyInsTrailers($safetyInsTrailers);
    }

    /**
     * {@inheritDoc}
     */
    public function getSafetyInsTrailers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSafetyInsTrailers', array());

        return parent::getSafetyInsTrailers();
    }

    /**
     * {@inheritDoc}
     */
    public function setSafetyInsVehicles($safetyInsVehicles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSafetyInsVehicles', array($safetyInsVehicles));

        return parent::setSafetyInsVehicles($safetyInsVehicles);
    }

    /**
     * {@inheritDoc}
     */
    public function getSafetyInsVehicles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSafetyInsVehicles', array());

        return parent::getSafetyInsVehicles();
    }

    /**
     * {@inheritDoc}
     */
    public function setSafetyIns($safetyIns)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSafetyIns', array($safetyIns));

        return parent::setSafetyIns($safetyIns);
    }

    /**
     * {@inheritDoc}
     */
    public function getSafetyIns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSafetyIns', array());

        return parent::getSafetyIns();
    }

    /**
     * {@inheritDoc}
     */
    public function setSafetyInsVaries($safetyInsVaries)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSafetyInsVaries', array($safetyInsVaries));

        return parent::setSafetyInsVaries($safetyInsVaries);
    }

    /**
     * {@inheritDoc}
     */
    public function getSafetyInsVaries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSafetyInsVaries', array());

        return parent::getSafetyInsVaries();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiFlag($niFlag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiFlag', array($niFlag));

        return parent::setNiFlag($niFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiFlag', array());

        return parent::getNiFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setTachographInsName($tachographInsName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTachographInsName', array($tachographInsName));

        return parent::setTachographInsName($tachographInsName);
    }

    /**
     * {@inheritDoc}
     */
    public function getTachographInsName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTachographInsName', array());

        return parent::getTachographInsName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPsvDiscsToBePrintedNo($psvDiscsToBePrintedNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPsvDiscsToBePrintedNo', array($psvDiscsToBePrintedNo));

        return parent::setPsvDiscsToBePrintedNo($psvDiscsToBePrintedNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPsvDiscsToBePrintedNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPsvDiscsToBePrintedNo', array());

        return parent::getPsvDiscsToBePrintedNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTranslateToWelsh($translateToWelsh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTranslateToWelsh', array($translateToWelsh));

        return parent::setTranslateToWelsh($translateToWelsh);
    }

    /**
     * {@inheritDoc}
     */
    public function getTranslateToWelsh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTranslateToWelsh', array());

        return parent::getTranslateToWelsh();
    }

    /**
     * {@inheritDoc}
     */
    public function clearProperties($properties = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearProperties', array($properties));

        return parent::clearProperties($properties);
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicenceType($licenceType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicenceType', array($licenceType));

        return parent::setLicenceType($licenceType);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicenceType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenceType', array());

        return parent::getLicenceType();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoodsOrPsv($goodsOrPsv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoodsOrPsv', array($goodsOrPsv));

        return parent::setGoodsOrPsv($goodsOrPsv);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoodsOrPsv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoodsOrPsv', array());

        return parent::getGoodsOrPsv();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastModifiedBy($lastModifiedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastModifiedBy', array($lastModifiedBy));

        return parent::setLastModifiedBy($lastModifiedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastModifiedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastModifiedBy', array());

        return parent::getLastModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrafficArea($trafficArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrafficArea', array($trafficArea));

        return parent::setTrafficArea($trafficArea);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrafficArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrafficArea', array());

        return parent::getTrafficArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganisation($organisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganisation', array($organisation));

        return parent::setOrganisation($organisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganisation', array());

        return parent::getOrganisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicNo($licNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicNo', array($licNo));

        return parent::setLicNo($licNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicNo', array());

        return parent::getLicNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setViAction($viAction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViAction', array($viAction));

        return parent::setViAction($viAction);
    }

    /**
     * {@inheritDoc}
     */
    public function getViAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViAction', array());

        return parent::getViAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotAuthTrailers($totAuthTrailers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotAuthTrailers', array($totAuthTrailers));

        return parent::setTotAuthTrailers($totAuthTrailers);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotAuthTrailers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotAuthTrailers', array());

        return parent::getTotAuthTrailers();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotAuthVehicles($totAuthVehicles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotAuthVehicles', array($totAuthVehicles));

        return parent::setTotAuthVehicles($totAuthVehicles);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotAuthVehicles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotAuthVehicles', array());

        return parent::getTotAuthVehicles();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotAuthSmallVehicles($totAuthSmallVehicles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotAuthSmallVehicles', array($totAuthSmallVehicles));

        return parent::setTotAuthSmallVehicles($totAuthSmallVehicles);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotAuthSmallVehicles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotAuthSmallVehicles', array());

        return parent::getTotAuthSmallVehicles();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotAuthMediumVehicles($totAuthMediumVehicles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotAuthMediumVehicles', array($totAuthMediumVehicles));

        return parent::setTotAuthMediumVehicles($totAuthMediumVehicles);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotAuthMediumVehicles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotAuthMediumVehicles', array());

        return parent::getTotAuthMediumVehicles();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotAuthLargeVehicles($totAuthLargeVehicles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotAuthLargeVehicles', array($totAuthLargeVehicles));

        return parent::setTotAuthLargeVehicles($totAuthLargeVehicles);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotAuthLargeVehicles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotAuthLargeVehicles', array());

        return parent::getTotAuthLargeVehicles();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotCommunityLicences($totCommunityLicences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotCommunityLicences', array($totCommunityLicences));

        return parent::setTotCommunityLicences($totCommunityLicences);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotCommunityLicences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotCommunityLicences', array());

        return parent::getTotCommunityLicences();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiryDate($expiryDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiryDate', array($expiryDate));

        return parent::setExpiryDate($expiryDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiryDate', array());

        return parent::getExpiryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setInForceDate($inForceDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInForceDate', array($inForceDate));

        return parent::setInForceDate($inForceDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInForceDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInForceDate', array());

        return parent::getInForceDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn($createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', array($createdOn));

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', array());

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOnBeforePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOnBeforePersist', array());

        return parent::setCreatedOnBeforePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastModifiedOn($lastModifiedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastModifiedOn', array($lastModifiedOn));

        return parent::setLastModifiedOn($lastModifiedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastModifiedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastModifiedOn', array());

        return parent::getLastModifiedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastModifiedOnBeforeUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastModifiedOnBeforeUpdate', array());

        return parent::setLastModifiedOnBeforeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', array($version));

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', array());

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersionBeforePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersionBeforePersist', array());

        return parent::setVersionBeforePersist();
    }

}
