<head>
    
    <meta charset="utf-8">
    
    <?php
        if (isset($pageTitle)) {
            echo $this->headTitle(strip_tags($pageTitle))
                ->append($this->translate('header-vehicle-operator-licensing', 'snapshot'))
                ->append($this->translate('header-gov.uk', 'snapshot'))
                ->setSeparator(' - ');
        }
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headScript();
        echo $this->headLink()->appendStylesheet($this->assetPath('/styles/print.css'), ['media' => 'screen, print']);
    ?>
    
</head>
