<p>Thank you for your EBSR Data Refresh submission received on <?php echo $this->submissionDate ?> for the
    following local bus service - <?php echo $this->registrationNumber; ?> - between
    <?php echo $this->origin; ?> and <?php echo $this->destination; ?> with service number
    <?php echo $this->lineName; ?> to come
    into effect on <?php echo $this->startDate; ?>.</p>

<p>Your submission has been accepted and our existing manual records have now been updated with the Electronic Bus Service Registration (EBSR) file.</p>

<p>We have copied this e-mail to the following local authorities: <?php echo $this->localAuthoritys; ?>.</p>

<p>You will find a copy of the PDF version of the registered particulars in your document area.
    Please check the contents and let us know if there are any discrepancies so we can correct them as quickly as possible.</p>

<p>Please do not reply directly to this e-mail by using the ‘Reply’
    button in your e-mail application as this is an automated facility
    that cannot handle incoming e-mails.
    If you need to contact us, please ring your usual
    caseworker or e-mail: <a href="mailto:self.service@otc.gsi.gov.uk">self.service@otc.gsi.gov.uk</a></p>