<p>Thank you for your EBSR application received on <?php echo $this->submissionDate ?> to withdraw
    the following local bus service - <?php echo $this->registrationNumber; ?> - between <Origin> and <Destination>
    with service number <?php echo $this->lineName; ?> is withdrawn.</p>

<p>Please do not reply directly to this e-mail by using the ‘Reply’ button in your e-mail application
    as this is an automated facility that cannot handle incoming e-mails.
    If you need to contact us, please ring your usual caseworker or e-mail: <a href="mailto:self.service@otc.gsi.gov.uk">self.service@otc.gsi.gov.uk</a></p>
