%s
%s
<strong>
    Gweler yr ymgymeriadau trwydded isod fel nodyn atgoffa o’ch goblygiadau:
</strong>
<ul class="list--bullet">
    <li>mae’r deddfwriaethau sy’n gysylltiedig â gyrru a gweithredu’r cerbydau a ddefnyddir dan y drwydded hon yn cael
        eu parchu;
    </li>
    <li>
        mae’r rheolau ynghylch oriau a thacograffiau gyrwyr yn cael eu parchu, cedwir cofnodion cywir a bod y rhain ar
        gael ar gais;
    </li>
    <li>cerbydau bach ac ôl-gerbydau bach yn cael eu gorlwytho;</li>
    <li>mae cerbydau’n gweithredu o fewn y cyfyngderau cyflymder;</li>
    <li>cedwir cerbydau ac ôl-gerbydau, gan gynnwys cerbydau ac ôl-gerbydau sy’n cael eu hurio, mewn cyflwr da ac wedi
        eu trin;
    </li>
    <li>mae gyrwyr yn adrodd ar unrhyw ddiffygion neu arwyddion o ddiffygion yn brydlon, sef diffygion a allai atal y
        cerbydau rhag cael eu gyrru’n ddiogel ynghyd â/ neu ôl-gerbydau, ac y cofnodir unrhyw ddiffygion yn
        ysgrifenedig;
    </li>
    <li>
        cedwir cofnodion (am 15 mis) o bob cofnod o ddiffygion gan yrwyr, ynghyd ag unrhyw archwiliad diogelwch, gwaith
        cynnal a chadw arferol ac atgyweiriadau i gerbydau, a’u bod ar gael ar gais;
    </li>
    <li>
        mewn perthynas â phob canolfan weithredu a ddynodir, na fydd y nifer o gerbydau ac ôl-gerbydau a gedwir yno yn
        fwy na’r uchafswm o awdurdodir ym mhob canolfan weithredu (a nodir ar y drwydded);
    </li>
    <li>ni ddefnyddir canolfan weithredu anawdurdodedig mewn unrhyw ardal draffig;</li>
    <li>
        ymhellach, byddaf yn hysbysu’r comisiynydd traffig o unrhyw gollfarnau yn fy erbyn i, neu’r cwmni, partner(iaid)
        busnes, cyfarwyddwyr y cwmni, rheolw(y)r trafnidiaeth a enwebwyd ac a enwyd yn y cais hwn, neu gyflogeion neu
        asiantwyr yr ymgeisydd am y drwydded hon ac, os cyhoeddir y drwydded, gollfarnau yn erbyn deilydd y drwydded neu
        gyflogeion neu asiantwyr deilydd y drwydded;
    </li>
    <li>
        byddaf yn sicrhau yr hysbysir y Comisiynydd Traffig cyn pen 28 diwrnod ynghylch unrhyw newid arall, er
        enghraifft i’r trefniadau cynnal a chadw a gynigir; newid yn statws ariannol deilydd y drwydded (e.e. os daw y
        cwmni i ben neu fynd i ddwylo derbynnydd), neu newid i fod yn Gwmni Cyfyngedig neu bartneriaeth, (gan gynnwys
        newidiadau yn enw’r cyfarwyddwyr neu’r partneriaid, a allai effeithio ar y drwydded os caiff ei chyhoeddi.
    </li>
    %s
</ul>