<li>
    Cytunaf i gael trefniant ffurfiol mewn grym i gael mynediad bob amser at o leiaf un cerbyd gwasanaeth cyhoeddus sydd
    wedi ei gofrestru neu sy’n gweithredu ym Mhrydain Fawr. Byddaf un ai’n darparu manylion cerbyd sy’n eiddo’n llwyr i
    mi a’i ddefnyddio dan y drwydded neu drwy ddangos ar gais fod gennyf i gerbyd ar gael dan drwy hur-bwrcasu,
    trefniant llogi/prydlesu neu fath arall o drefniant ffurfiol.
</li>