<p>
    Deallaf drwy arwyddo’r cais hwn fy mod yn derbyn yr ymgymeriadau isod; y byddant yn cael eu cofnodi  ar y
    drwydded; y gallai methu â chydymffurfio a’r amodau neu’r ymgymeriadau a gofnodwyd ar y drwydded olygu  y caiff y
    drwydded ei dirymu, ei hatal neu ei chyfyngu; a bod methu â chydymffurfio â’r amodau hyn hefyd yn  drosedd. 
</p>
<ul class="list--bullet"> 
    <li>Mae’r deddfwriaethau sy’n gysylltiedig â gyrru a gweithredu’r cerbydau a ddefnyddir dan y drwydded hon yn cael
        eu parchu;
    </li>
    <li>  Mae’r rheolau ynghylch oriau a thacograffiau gyrwyr yn cael eu parchu, cedwir cofnodion cywir a bod y rhain 
        ar gael ar gais; 
    </li>
    <li>Nid yw cerbydau ac ôl-gerbydau yn cael eu gorlwytho;</li>
    <li>Mae cerbydau’n gweithredu o fewn y cyfyngderau cyflymder;</li>
    <li>Cedwir cerbydau ac ôl-gerbydau, gan gynnwys cerbydau ac ôl-gerbydau sy’n cael eu hurio, mewn cyflwr da ac wedi
        eu trin;
    </li>
    <li>  Mae gyrwyr yn adrodd ar unrhyw ddiffygion neu arwyddion o ddiffygion yn brydlon, sef diffygion a allai atal y
        cerbydau rhag cael eu gyrru’n ddiogel  ynghyd â/ neu ôl-gerbydau, ac y cofnodir unrhyw ddiffygion yn
        ysgrifenedig; 
    </li>
    <li>  Cedwir cofnodion (am 15 mis) o bob cofnod o ddiffygion gan yrwyr, ynghyd ag unrhyw archwiliad diogelwch,
        gwaith cynnal a chadw  arferol ac atgyweiriadau i gerbydau, a’u bod ar gael ar gais; 
    </li>
    <li>  Mewn perthynas â phob canolfan weithredu a ddynodir, na fydd y nifer o gerbydau ac ôl-gerbydau a gedwir yno 
        yn fwy na’r uchafswm o awdurdodir ym mhob canolfan weithredu (a nodir ar y drwydded); 
    </li>
    <li>Ni ddefnyddir canolfan weithredu anawdurdodedig mewn unrhyw ardal draffig;</li>
    <li>  Ymhellach, byddaf yn hysbysu’r Comisiynydd Traffig o unrhyw gollfarnau yn fy erbyn i, neu’r cwmni,
        partner(iaid)  busnes, cyfarwyddwyr y cwmni, rheolw(y)r trafnidiaeth a enwebwyd ac a enwyd yn y cais hwn, neu
        gyflogeion neu  asiantwyr yr ymgeisydd am y drwydded hon ac, os cyhoeddir y drwydded, gollfarnau yn erbyn
        deilydd y drwydded  neu gyflogeion neu asiantwyr deilydd y drwydded; 
    </li>
    <li>  Byddaf yn sicrhau yr hysbysir y Comisiynydd Traffig cyn pen 28 diwrnod ynghylch unrhyw newid arall, er
        enghraifft  i’r trefniadau cynnal a chadw a gynigir; newid yn statws ariannol deilydd y drwydded (e.e. os  daw y
        cwmni i ben neu fynd i ddwylo derbynnydd), neu newid i fod yn Gwmni Cyfyngedig neu bartneriaeth, a allai
        effeithio  ar y drwydded os caiff ei chyhoeddi. 
    </li>
      %s 
</ul>
 %s 