<p><strong>Trwy lofnodi’r datganiad ar yr holiadur rydych yn cadarnhau eich statws fel rheolwr trafnidiaeth mewnol, rheolwr trafnidiaeth allanol neu’r ddau.</strong></p>
<p>Rwy’n cadarnhau fod:</p>
<ul class="list--bullet">
    <li>Y byddaf yn rheoli gweithgareddau trafnidiaeth deiliad y drwydded/ymgeisydd yn effeithiol a pharhaus; a</li>
    <li>Bod gennyf gysylltiad gwirioneddol â deiliad y drwydded/yr ymgeisydd; a</li>
    <li>Rwyf yn preswylio yn y Gymuned Ewropeaidd;</li>
</ul>

<p>Rwy’n deall fod fy nghyfrifoldebau yn cynnwys:</p>
<ul class="list--bullet">
    <li>Gwneud trefniadau i sicrhau bod gyrwyr yn cydymffurfio â rheolau oriau gyrwyr a thacograff ac â chyfyngiadau cyflymder;</li>
    <li>Gwneud trefniadau i sicrhau bod y cerbydau yn cael eu cynnal a’u cadw yn briodol, gan gynnwys arolygu cerbydau ar yr amser priodol a’r gweithredu i gywiro unrhyw ddiffygion a ddarganfyddir;</li>
    <li>Adrodd a chofnodi diffygion cerbydau gan yrwyr;</li>
    <li>Dull llunio a chywirdeb yr holl gofnodion, y mae’n rhaid eu cadw am gyfnod o ddim llai na 15 mis;</li>
    <li>Gwneud trefniadau i sicrhau na fydd y cerbyd/cerbydau yn cael eu gorlwytho;</li>
    <li>Sicrhau bod y cerbydau a awdurdodwyd yn cael eu cadw yn y ganolfan/canolfannau gweithredu a awdurdodwyd pan na fyddant yn cael eu defnyddio;</li>
    <li>Pan fydd hynny’n addas, hysbysu’r comisiynydd traffig perthnasol (yn ysgrifenedig) o’r holl erlyniadau a chollfarnau yn ymwneud â’r gweithredwr, y gyrwyr a fi cyn pen 28 diwrnod o’r gwrandawiad llys; a</li>
    <li>Hysbysu’r comisiynydd traffig perthnasol o’m hymddiswyddiad.</li>
</ul>

<p>
    <strong>Os byddaf yn methu â bodloni unrhyw un o’r gofynion rwy’n deall y gallai comisiynydd traffig fy anghymhwyso rhag bod yn rheolwr trafnidiaeth mewn unrhyw wlad yn yr Undeb Ewropeaidd</strong>
</p>