name: Trigger GH Actions Workflow

on:
  workflow_call:
    secrets:
      gh_token:
        required: true

jobs:

  trigger-gh-workflow:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

    - name: Trigger Workflow
      run: |
        gh workflow run 'CD NON-PROD VOL API' \
          -R dvsa/dvsa-container-registry \
          --ref feature/AWSRESET1-514 \
          -f vol_api_image_tag=vol-api-7.4.33-alpine-fpm-ddea10a
      env:
        GITHUB_TOKEN: ${{ secrets.gh_token }}
    
    - name: Monitor Workflow Execution Progress
      run: |
        runID=`gh run list --workflow=nonprod-vol-api-manual-cd.yaml -R dvsa/dvsa-container-registry | sed -n 1p | awk '{ print $(NF-2) }'`
        gh run watch $runID -i1
      env:
        GITHUB_TOKEN: ${{ secrets.gh_token }}
