name: Trigger GH Actions Workflow

on:
  workflow_call:
    inputs:
      branch:
        description: 'Name of the branch which contains the given Workflow'
        default: 'main'
        required: true
        type: string
      git_repository:
        description: 'Name of the Owner/Repo which contains the given Workflow'
        default: ''
        required: true
        type: string
      workflow_name:
        description: 'Name of the given Workflow'
        default: ''
        required: true
        type: string
      vol_api_image_tag:
        description: 'VOL API image tag'
        default: ''
        required: true
        type: string
    secrets:
      gh_token:
        required: true

jobs:

  trigger-gh-workflow:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

    - name: Checkout the repository to the runner
      uses: actions/checkout@v3

    - name: Trigger Workflow
      run: |
        gh workflow run '${{ inputs.workflow_name }}' \
          -R ${{ inputs.git_repository }} \
          --ref ${{ inputs.branch }} \
          -f vol_api_image_tag=${{ inputs.vol_api_image_tag }}
        sleep 60 # required to assign the run-id to worflow
      env:
        GITHUB_TOKEN: ${{ secrets.gh_token }}
    # - name: Trigger Workflow
    #   run: |
    #     curl \
    #         -X POST \
    #         -H "authorization: Bearer  ${{ secrets.gh_token }}" \
    #         -H "Accept: application/vnd.github.v3+json" \
    #         https://api.github.com/repos/dvsa/dvsa-container-registry/actions/workflows/nonprod-vol-api-manual-cd.yaml/dispatches \
    #         -d '{"ref":"feature/AWSRESET1-514","inputs":{"vol_api_image_tag":"vol-api-7.4.33-alpine-fpm-ddea10a"}}'

    
    - name: Monitor Workflow Execution Progress 
      run: |
        runID=`curl -L -H \ 
                "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.gh_token }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ inputs.git_repository }}/actions/runs |\
                jq -r '.workflow_runs[0]|select(.name == "${{ inputs.workflow_name }}").id'`
        # Use the filter select(.name == "{ WORKFLOW_NAME }" and .status == "in_progress").id if no Perf issues for Git API
        gh run watch $runID --interval 10 --exit-status 1  -R ${{ inputs.git_repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.gh_token }}